// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ack/ack.proto

package ack

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_ack_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_ack_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_ack_ack_proto_rawDescGZIP(), []int{0}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_ack_ack_proto protoreflect.FileDescriptor

const file_ack_ack_proto_rawDesc = "" +
	"\n" +
	"\rack/ack.proto\x12\x03ack\"+\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB=Z;github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/ackb\x06proto3"

var (
	file_ack_ack_proto_rawDescOnce sync.Once
	file_ack_ack_proto_rawDescData []byte
)

func file_ack_ack_proto_rawDescGZIP() []byte {
	file_ack_ack_proto_rawDescOnce.Do(func() {
		file_ack_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ack_ack_proto_rawDesc), len(file_ack_ack_proto_rawDesc)))
	})
	return file_ack_ack_proto_rawDescData
}

var file_ack_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ack_ack_proto_goTypes = []any{
	(*Ack)(nil), // 0: ack.Ack
}
var file_ack_ack_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ack_ack_proto_init() }
func file_ack_ack_proto_init() {
	if File_ack_ack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ack_ack_proto_rawDesc), len(file_ack_ack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ack_ack_proto_goTypes,
		DependencyIndexes: file_ack_ack_proto_depIdxs,
		MessageInfos:      file_ack_ack_proto_msgTypes,
	}.Build()
	File_ack_ack_proto = out.File
	file_ack_ack_proto_goTypes = nil
	file_ack_ack_proto_depIdxs = nil
}
