// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: merkle/merkle.proto

package merkle

import (
	ack "github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/ack"
	phase "github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/phase"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerkleSnapshot struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Config  *SnapshotConfig        `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// State fields
	TotalBlocks        uint64 `protobuf:"varint,3,opt,name=total_blocks,json=totalBlocks,proto3" json:"total_blocks,omitempty"`
	ExpectedNextHeight uint64 `protobuf:"varint,4,opt,name=expected_next_height,json=expectedNextHeight,proto3" json:"expected_next_height,omitempty"`
	EnforceHeights     bool   `protobuf:"varint,5,opt,name=enforce_heights,json=enforceHeights,proto3" json:"enforce_heights,omitempty"`
	// Partial Chunk Buffer
	// InChunkElems contains the hashes of elements in the current partial chunk.
	InChunkElems [][]byte `protobuf:"bytes,6,rep,name=in_chunk_elems,json=inChunkElems,proto3" json:"in_chunk_elems,omitempty"`
	InChunkStart uint64   `protobuf:"varint,7,opt,name=in_chunk_start,json=inChunkStart,proto3" json:"in_chunk_start,omitempty"`
	// Outer Accumulator Peaks
	Peaks         []*SnapshotNode `protobuf:"bytes,8,rep,name=peaks,proto3" json:"peaks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleSnapshot) Reset() {
	*x = MerkleSnapshot{}
	mi := &file_merkle_merkle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleSnapshot) ProtoMessage() {}

func (x *MerkleSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_merkle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleSnapshot.ProtoReflect.Descriptor instead.
func (*MerkleSnapshot) Descriptor() ([]byte, []int) {
	return file_merkle_merkle_proto_rawDescGZIP(), []int{0}
}

func (x *MerkleSnapshot) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MerkleSnapshot) GetConfig() *SnapshotConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *MerkleSnapshot) GetTotalBlocks() uint64 {
	if x != nil {
		return x.TotalBlocks
	}
	return 0
}

func (x *MerkleSnapshot) GetExpectedNextHeight() uint64 {
	if x != nil {
		return x.ExpectedNextHeight
	}
	return 0
}

func (x *MerkleSnapshot) GetEnforceHeights() bool {
	if x != nil {
		return x.EnforceHeights
	}
	return false
}

func (x *MerkleSnapshot) GetInChunkElems() [][]byte {
	if x != nil {
		return x.InChunkElems
	}
	return nil
}

func (x *MerkleSnapshot) GetInChunkStart() uint64 {
	if x != nil {
		return x.InChunkStart
	}
	return 0
}

func (x *MerkleSnapshot) GetPeaks() []*SnapshotNode {
	if x != nil {
		return x.Peaks
	}
	return nil
}

type SnapshotConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockMerge    int32                  `protobuf:"varint,1,opt,name=block_merge,json=blockMerge,proto3" json:"block_merge,omitempty"`
	ExpectedTotal uint64                 `protobuf:"varint,2,opt,name=expected_total,json=expectedTotal,proto3" json:"expected_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotConfig) Reset() {
	*x = SnapshotConfig{}
	mi := &file_merkle_merkle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotConfig) ProtoMessage() {}

func (x *SnapshotConfig) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_merkle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotConfig.ProtoReflect.Descriptor instead.
func (*SnapshotConfig) Descriptor() ([]byte, []int) {
	return file_merkle_merkle_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotConfig) GetBlockMerge() int32 {
	if x != nil {
		return x.BlockMerge
	}
	return 0
}

func (x *SnapshotConfig) GetExpectedTotal() uint64 {
	if x != nil {
		return x.ExpectedTotal
	}
	return 0
}

type SnapshotNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          *SnapshotNode          `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right         *SnapshotNode          `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	Root          []byte                 `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	Start         uint64                 `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`
	Count         uint32                 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	HasData       bool                   `protobuf:"varint,7,opt,name=has_data,json=hasData,proto3" json:"has_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotNode) Reset() {
	*x = SnapshotNode{}
	mi := &file_merkle_merkle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotNode) ProtoMessage() {}

func (x *SnapshotNode) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_merkle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotNode.ProtoReflect.Descriptor instead.
func (*SnapshotNode) Descriptor() ([]byte, []int) {
	return file_merkle_merkle_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotNode) GetLeft() *SnapshotNode {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *SnapshotNode) GetRight() *SnapshotNode {
	if x != nil {
		return x.Right
	}
	return nil
}

func (x *SnapshotNode) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *SnapshotNode) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SnapshotNode) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SnapshotNode) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotNode) GetHasData() bool {
	if x != nil {
		return x.HasData
	}
	return false
}

type MerkleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Config        *SnapshotConfig        `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleRequest) Reset() {
	*x = MerkleRequest{}
	mi := &file_merkle_merkle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRequest) ProtoMessage() {}

func (x *MerkleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_merkle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRequest.ProtoReflect.Descriptor instead.
func (*MerkleRequest) Descriptor() ([]byte, []int) {
	return file_merkle_merkle_proto_rawDescGZIP(), []int{3}
}

func (x *MerkleRequest) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *MerkleRequest) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *MerkleRequest) GetConfig() *SnapshotConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type MerkleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *MerkleSnapshot        `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Ack           *ack.Ack               `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`
	Phase         *phase.Phase           `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleMessage) Reset() {
	*x = MerkleMessage{}
	mi := &file_merkle_merkle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleMessage) ProtoMessage() {}

func (x *MerkleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_merkle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleMessage.ProtoReflect.Descriptor instead.
func (*MerkleMessage) Descriptor() ([]byte, []int) {
	return file_merkle_merkle_proto_rawDescGZIP(), []int{4}
}

func (x *MerkleMessage) GetSnapshot() *MerkleSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *MerkleMessage) GetAck() *ack.Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *MerkleMessage) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

type MerkleRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *MerkleRequest         `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Ack           *ack.Ack               `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleRequestMessage) Reset() {
	*x = MerkleRequestMessage{}
	mi := &file_merkle_merkle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRequestMessage) ProtoMessage() {}

func (x *MerkleRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_merkle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRequestMessage.ProtoReflect.Descriptor instead.
func (*MerkleRequestMessage) Descriptor() ([]byte, []int) {
	return file_merkle_merkle_proto_rawDescGZIP(), []int{5}
}

func (x *MerkleRequestMessage) GetRequest() *MerkleRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *MerkleRequestMessage) GetAck() *ack.Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_merkle_merkle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_merkle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_merkle_merkle_proto_rawDescGZIP(), []int{6}
}

func (x *Range) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Range) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_merkle_merkle_proto protoreflect.FileDescriptor

const file_merkle_merkle_proto_rawDesc = "" +
	"\n" +
	"\x13merkle/merkle.proto\x12\x06merkle\x1a\rack/ack.proto\x1a\x11phase/phase.proto\"\xd0\x02\n" +
	"\x0eMerkleSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12.\n" +
	"\x06config\x18\x02 \x01(\v2\x16.merkle.SnapshotConfigR\x06config\x12!\n" +
	"\ftotal_blocks\x18\x03 \x01(\x04R\vtotalBlocks\x120\n" +
	"\x14expected_next_height\x18\x04 \x01(\x04R\x12expectedNextHeight\x12'\n" +
	"\x0fenforce_heights\x18\x05 \x01(\bR\x0eenforceHeights\x12$\n" +
	"\x0ein_chunk_elems\x18\x06 \x03(\fR\finChunkElems\x12$\n" +
	"\x0ein_chunk_start\x18\a \x01(\x04R\finChunkStart\x12*\n" +
	"\x05peaks\x18\b \x03(\v2\x14.merkle.SnapshotNodeR\x05peaks\"X\n" +
	"\x0eSnapshotConfig\x12\x1f\n" +
	"\vblock_merge\x18\x01 \x01(\x05R\n" +
	"blockMerge\x12%\n" +
	"\x0eexpected_total\x18\x02 \x01(\x04R\rexpectedTotal\"\xd3\x01\n" +
	"\fSnapshotNode\x12(\n" +
	"\x04left\x18\x01 \x01(\v2\x14.merkle.SnapshotNodeR\x04left\x12*\n" +
	"\x05right\x18\x02 \x01(\v2\x14.merkle.SnapshotNodeR\x05right\x12\x12\n" +
	"\x04root\x18\x03 \x01(\fR\x04root\x12\x14\n" +
	"\x05start\x18\x04 \x01(\x04R\x05start\x12\x14\n" +
	"\x05count\x18\x05 \x01(\rR\x05count\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x19\n" +
	"\bhas_data\x18\a \x01(\bR\ahasData\"g\n" +
	"\rMerkleRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\x12.\n" +
	"\x06config\x18\x03 \x01(\v2\x16.merkle.SnapshotConfigR\x06config\"\x83\x01\n" +
	"\rMerkleMessage\x122\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x16.merkle.MerkleSnapshotR\bsnapshot\x12\x1a\n" +
	"\x03ack\x18\x02 \x01(\v2\b.ack.AckR\x03ack\x12\"\n" +
	"\x05phase\x18\x03 \x01(\v2\f.phase.PhaseR\x05phase\"c\n" +
	"\x14MerkleRequestMessage\x12/\n" +
	"\arequest\x18\x01 \x01(\v2\x15.merkle.MerkleRequestR\arequest\x12\x1a\n" +
	"\x03ack\x18\x02 \x01(\v2\b.ack.AckR\x03ack\"/\n" +
	"\x05range\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03endB@Z>github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/merkleb\x06proto3"

var (
	file_merkle_merkle_proto_rawDescOnce sync.Once
	file_merkle_merkle_proto_rawDescData []byte
)

func file_merkle_merkle_proto_rawDescGZIP() []byte {
	file_merkle_merkle_proto_rawDescOnce.Do(func() {
		file_merkle_merkle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merkle_merkle_proto_rawDesc), len(file_merkle_merkle_proto_rawDesc)))
	})
	return file_merkle_merkle_proto_rawDescData
}

var file_merkle_merkle_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_merkle_merkle_proto_goTypes = []any{
	(*MerkleSnapshot)(nil),       // 0: merkle.MerkleSnapshot
	(*SnapshotConfig)(nil),       // 1: merkle.SnapshotConfig
	(*SnapshotNode)(nil),         // 2: merkle.SnapshotNode
	(*MerkleRequest)(nil),        // 3: merkle.MerkleRequest
	(*MerkleMessage)(nil),        // 4: merkle.MerkleMessage
	(*MerkleRequestMessage)(nil), // 5: merkle.MerkleRequestMessage
	(*Range)(nil),                // 6: merkle.range
	(*ack.Ack)(nil),              // 7: ack.Ack
	(*phase.Phase)(nil),          // 8: phase.Phase
}
var file_merkle_merkle_proto_depIdxs = []int32{
	1,  // 0: merkle.MerkleSnapshot.config:type_name -> merkle.SnapshotConfig
	2,  // 1: merkle.MerkleSnapshot.peaks:type_name -> merkle.SnapshotNode
	2,  // 2: merkle.SnapshotNode.left:type_name -> merkle.SnapshotNode
	2,  // 3: merkle.SnapshotNode.right:type_name -> merkle.SnapshotNode
	1,  // 4: merkle.MerkleRequest.config:type_name -> merkle.SnapshotConfig
	0,  // 5: merkle.MerkleMessage.snapshot:type_name -> merkle.MerkleSnapshot
	7,  // 6: merkle.MerkleMessage.ack:type_name -> ack.Ack
	8,  // 7: merkle.MerkleMessage.phase:type_name -> phase.Phase
	3,  // 8: merkle.MerkleRequestMessage.request:type_name -> merkle.MerkleRequest
	7,  // 9: merkle.MerkleRequestMessage.ack:type_name -> ack.Ack
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_merkle_merkle_proto_init() }
func file_merkle_merkle_proto_init() {
	if File_merkle_merkle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merkle_merkle_proto_rawDesc), len(file_merkle_merkle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_merkle_merkle_proto_goTypes,
		DependencyIndexes: file_merkle_merkle_proto_depIdxs,
		MessageInfos:      file_merkle_merkle_proto_msgTypes,
	}.Build()
	File_merkle_merkle_proto = out.File
	file_merkle_merkle_proto_goTypes = nil
	file_merkle_merkle_proto_depIdxs = nil
}
