// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: tagging/tag.proto

package tagging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   []uint64               `protobuf:"varint,1,rep,packed,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_tagging_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_tagging_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_tagging_tag_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetBlockNumber() []uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return nil
}

var File_tagging_tag_proto protoreflect.FileDescriptor

const file_tagging_tag_proto_rawDesc = "" +
	"\n" +
	"\x11tagging/tag.proto\x12\atagging\"(\n" +
	"\x03Tag\x12!\n" +
	"\fblock_number\x18\x01 \x03(\x04R\vblockNumberBAZ?github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/taggingb\x06proto3"

var (
	file_tagging_tag_proto_rawDescOnce sync.Once
	file_tagging_tag_proto_rawDescData []byte
)

func file_tagging_tag_proto_rawDescGZIP() []byte {
	file_tagging_tag_proto_rawDescOnce.Do(func() {
		file_tagging_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tagging_tag_proto_rawDesc), len(file_tagging_tag_proto_rawDesc)))
	})
	return file_tagging_tag_proto_rawDescData
}

var file_tagging_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tagging_tag_proto_goTypes = []any{
	(*Tag)(nil), // 0: tagging.Tag
}
var file_tagging_tag_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tagging_tag_proto_init() }
func file_tagging_tag_proto_init() {
	if File_tagging_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tagging_tag_proto_rawDesc), len(file_tagging_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tagging_tag_proto_goTypes,
		DependencyIndexes: file_tagging_tag_proto_depIdxs,
		MessageInfos:      file_tagging_tag_proto_msgTypes,
	}.Build()
	File_tagging_tag_proto = out.File
	file_tagging_tag_proto_goTypes = nil
	file_tagging_tag_proto_depIdxs = nil
}
