// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: priorsync/priorsync.proto

package priorsync

import (
	ack "github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/ack"
	nodeinfo "github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/nodeinfo"
	phase "github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/phase"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriorSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocknumber   uint64                 `protobuf:"varint,1,opt,name=blocknumber,proto3" json:"blocknumber,omitempty"`
	Stateroot     []byte                 `protobuf:"bytes,2,opt,name=stateroot,proto3" json:"stateroot,omitempty"`
	Blockhash     []byte                 `protobuf:"bytes,3,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorSync) Reset() {
	*x = PriorSync{}
	mi := &file_priorsync_priorsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorSync) ProtoMessage() {}

func (x *PriorSync) ProtoReflect() protoreflect.Message {
	mi := &file_priorsync_priorsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorSync.ProtoReflect.Descriptor instead.
func (*PriorSync) Descriptor() ([]byte, []int) {
	return file_priorsync_priorsync_proto_rawDescGZIP(), []int{0}
}

func (x *PriorSync) GetBlocknumber() uint64 {
	if x != nil {
		return x.Blocknumber
	}
	return 0
}

func (x *PriorSync) GetStateroot() []byte {
	if x != nil {
		return x.Stateroot
	}
	return nil
}

func (x *PriorSync) GetBlockhash() []byte {
	if x != nil {
		return x.Blockhash
	}
	return nil
}

func (x *PriorSync) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksum      []byte                 `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Nodeinfo      *nodeinfo.NodeInfo     `protobuf:"bytes,4,opt,name=nodeinfo,proto3" json:"nodeinfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_priorsync_priorsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_priorsync_priorsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_priorsync_priorsync_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *Metadata) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Metadata) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Metadata) GetNodeinfo() *nodeinfo.NodeInfo {
	if x != nil {
		return x.Nodeinfo
	}
	return nil
}

type PriorSyncMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priorsync     *PriorSync             `protobuf:"bytes,1,opt,name=priorsync,proto3" json:"priorsync,omitempty"`
	Ack           *ack.PriorSyncAck      `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`
	Phase         *phase.Phase           `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorSyncMessage) Reset() {
	*x = PriorSyncMessage{}
	mi := &file_priorsync_priorsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorSyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorSyncMessage) ProtoMessage() {}

func (x *PriorSyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_priorsync_priorsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorSyncMessage.ProtoReflect.Descriptor instead.
func (*PriorSyncMessage) Descriptor() ([]byte, []int) {
	return file_priorsync_priorsync_proto_rawDescGZIP(), []int{2}
}

func (x *PriorSyncMessage) GetPriorsync() *PriorSync {
	if x != nil {
		return x.Priorsync
	}
	return nil
}

func (x *PriorSyncMessage) GetAck() *ack.PriorSyncAck {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *PriorSyncMessage) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

var File_priorsync_priorsync_proto protoreflect.FileDescriptor

const file_priorsync_priorsync_proto_rawDesc = "" +
	"\n" +
	"\x19priorsync/priorsync.proto\x12\tpriorsync\x1a\x17nodeinfo/nodeinfo.proto\x1a\rack/ack.proto\x1a\x11phase/phase.proto\"\x9a\x01\n" +
	"\tPriorSync\x12 \n" +
	"\vblocknumber\x18\x01 \x01(\x04R\vblocknumber\x12\x1c\n" +
	"\tstateroot\x18\x02 \x01(\fR\tstateroot\x12\x1c\n" +
	"\tblockhash\x18\x03 \x01(\fR\tblockhash\x12/\n" +
	"\bmetadata\x18\x04 \x01(\v2\x13.priorsync.MetadataR\bmetadata\"\x86\x01\n" +
	"\bMetadata\x12\x1a\n" +
	"\bchecksum\x18\x01 \x01(\fR\bchecksum\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12.\n" +
	"\bnodeinfo\x18\x04 \x01(\v2\x12.nodeinfo.NodeInfoR\bnodeinfo\"\x8f\x01\n" +
	"\x10PriorSyncMessage\x122\n" +
	"\tpriorsync\x18\x01 \x01(\v2\x14.priorsync.PriorSyncR\tpriorsync\x12#\n" +
	"\x03ack\x18\x02 \x01(\v2\x11.ack.PriorSyncAckR\x03ack\x12\"\n" +
	"\x05phase\x18\x03 \x01(\v2\f.phase.PhaseR\x05phaseBCZAgithub.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/priorsyncb\x06proto3"

var (
	file_priorsync_priorsync_proto_rawDescOnce sync.Once
	file_priorsync_priorsync_proto_rawDescData []byte
)

func file_priorsync_priorsync_proto_rawDescGZIP() []byte {
	file_priorsync_priorsync_proto_rawDescOnce.Do(func() {
		file_priorsync_priorsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_priorsync_priorsync_proto_rawDesc), len(file_priorsync_priorsync_proto_rawDesc)))
	})
	return file_priorsync_priorsync_proto_rawDescData
}

var file_priorsync_priorsync_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_priorsync_priorsync_proto_goTypes = []any{
	(*PriorSync)(nil),         // 0: priorsync.PriorSync
	(*Metadata)(nil),          // 1: priorsync.Metadata
	(*PriorSyncMessage)(nil),  // 2: priorsync.PriorSyncMessage
	(*nodeinfo.NodeInfo)(nil), // 3: nodeinfo.NodeInfo
	(*ack.PriorSyncAck)(nil),  // 4: ack.PriorSyncAck
	(*phase.Phase)(nil),       // 5: phase.Phase
}
var file_priorsync_priorsync_proto_depIdxs = []int32{
	1, // 0: priorsync.PriorSync.metadata:type_name -> priorsync.Metadata
	3, // 1: priorsync.Metadata.nodeinfo:type_name -> nodeinfo.NodeInfo
	0, // 2: priorsync.PriorSyncMessage.priorsync:type_name -> priorsync.PriorSync
	4, // 3: priorsync.PriorSyncMessage.ack:type_name -> ack.PriorSyncAck
	5, // 4: priorsync.PriorSyncMessage.phase:type_name -> phase.Phase
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_priorsync_priorsync_proto_init() }
func file_priorsync_priorsync_proto_init() {
	if File_priorsync_priorsync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_priorsync_priorsync_proto_rawDesc), len(file_priorsync_priorsync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_priorsync_priorsync_proto_goTypes,
		DependencyIndexes: file_priorsync_priorsync_proto_depIdxs,
		MessageInfos:      file_priorsync_priorsync_proto_msgTypes,
	}.Build()
	File_priorsync_priorsync_proto = out.File
	file_priorsync_priorsync_proto_goTypes = nil
	file_priorsync_priorsync_proto_depIdxs = nil
}
