// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: priorsync/priorsync.proto

package priorsync

import (
	ack "github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/ack"
	merkle "github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/merkle"
	nodeinfo "github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/nodeinfo"
	phase "github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/phase"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriorSync struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Blocknumber    uint64                 `protobuf:"varint,1,opt,name=blocknumber,proto3" json:"blocknumber,omitempty"`
	Stateroot      []byte                 `protobuf:"bytes,2,opt,name=stateroot,proto3" json:"stateroot,omitempty"`
	Blockhash      []byte                 `protobuf:"bytes,3,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	Metadata       *Metadata              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Merklesnapshot *merkle.MerkleSnapshot `protobuf:"bytes,5,opt,name=merklesnapshot,proto3" json:"merklesnapshot,omitempty"`
	Range          *merkle.Range          `protobuf:"bytes,6,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PriorSync) Reset() {
	*x = PriorSync{}
	mi := &file_priorsync_priorsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorSync) ProtoMessage() {}

func (x *PriorSync) ProtoReflect() protoreflect.Message {
	mi := &file_priorsync_priorsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorSync.ProtoReflect.Descriptor instead.
func (*PriorSync) Descriptor() ([]byte, []int) {
	return file_priorsync_priorsync_proto_rawDescGZIP(), []int{0}
}

func (x *PriorSync) GetBlocknumber() uint64 {
	if x != nil {
		return x.Blocknumber
	}
	return 0
}

func (x *PriorSync) GetStateroot() []byte {
	if x != nil {
		return x.Stateroot
	}
	return nil
}

func (x *PriorSync) GetBlockhash() []byte {
	if x != nil {
		return x.Blockhash
	}
	return nil
}

func (x *PriorSync) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PriorSync) GetMerklesnapshot() *merkle.MerkleSnapshot {
	if x != nil {
		return x.Merklesnapshot
	}
	return nil
}

func (x *PriorSync) GetRange() *merkle.Range {
	if x != nil {
		return x.Range
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksum      []byte                 `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Nodeinfo      *nodeinfo.NodeInfo     `protobuf:"bytes,4,opt,name=nodeinfo,proto3" json:"nodeinfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_priorsync_priorsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_priorsync_priorsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_priorsync_priorsync_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *Metadata) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Metadata) GetNodeinfo() *nodeinfo.NodeInfo {
	if x != nil {
		return x.Nodeinfo
	}
	return nil
}

type PriorSyncMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priorsync     *PriorSync             `protobuf:"bytes,1,opt,name=priorsync,proto3" json:"priorsync,omitempty"`
	Ack           *ack.Ack               `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`
	Phase         *phase.Phase           `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorSyncMessage) Reset() {
	*x = PriorSyncMessage{}
	mi := &file_priorsync_priorsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorSyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorSyncMessage) ProtoMessage() {}

func (x *PriorSyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_priorsync_priorsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorSyncMessage.ProtoReflect.Descriptor instead.
func (*PriorSyncMessage) Descriptor() ([]byte, []int) {
	return file_priorsync_priorsync_proto_rawDescGZIP(), []int{2}
}

func (x *PriorSyncMessage) GetPriorsync() *PriorSync {
	if x != nil {
		return x.Priorsync
	}
	return nil
}

func (x *PriorSyncMessage) GetAck() *ack.Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *PriorSyncMessage) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

type StreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamMessage_PriorSync
	//	*StreamMessage_Merkle
	//	*StreamMessage_MerkleReq
	Payload       isStreamMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_priorsync_priorsync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_priorsync_priorsync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_priorsync_priorsync_proto_rawDescGZIP(), []int{3}
}

func (x *StreamMessage) GetPayload() isStreamMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamMessage) GetPriorSync() *PriorSyncMessage {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_PriorSync); ok {
			return x.PriorSync
		}
	}
	return nil
}

func (x *StreamMessage) GetMerkle() *merkle.MerkleMessage {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_Merkle); ok {
			return x.Merkle
		}
	}
	return nil
}

func (x *StreamMessage) GetMerkleReq() *merkle.MerkleRequestMessage {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_MerkleReq); ok {
			return x.MerkleReq
		}
	}
	return nil
}

type isStreamMessage_Payload interface {
	isStreamMessage_Payload()
}

type StreamMessage_PriorSync struct {
	PriorSync *PriorSyncMessage `protobuf:"bytes,1,opt,name=prior_sync,json=priorSync,proto3,oneof"`
}

type StreamMessage_Merkle struct {
	Merkle *merkle.MerkleMessage `protobuf:"bytes,2,opt,name=merkle,proto3,oneof"`
}

type StreamMessage_MerkleReq struct {
	MerkleReq *merkle.MerkleRequestMessage `protobuf:"bytes,3,opt,name=merkle_req,json=merkleReq,proto3,oneof"`
}

func (*StreamMessage_PriorSync) isStreamMessage_Payload() {}

func (*StreamMessage_Merkle) isStreamMessage_Payload() {}

func (*StreamMessage_MerkleReq) isStreamMessage_Payload() {}

var File_priorsync_priorsync_proto protoreflect.FileDescriptor

const file_priorsync_priorsync_proto_rawDesc = "" +
	"\n" +
	"\x19priorsync/priorsync.proto\x12\tpriorsync\x1a\x17nodeinfo/nodeinfo.proto\x1a\rack/ack.proto\x1a\x11phase/phase.proto\x1a\x13merkle/merkle.proto\"\xff\x01\n" +
	"\tPriorSync\x12 \n" +
	"\vblocknumber\x18\x01 \x01(\x04R\vblocknumber\x12\x1c\n" +
	"\tstateroot\x18\x02 \x01(\fR\tstateroot\x12\x1c\n" +
	"\tblockhash\x18\x03 \x01(\fR\tblockhash\x12/\n" +
	"\bmetadata\x18\x04 \x01(\v2\x13.priorsync.MetadataR\bmetadata\x12>\n" +
	"\x0emerklesnapshot\x18\x05 \x01(\v2\x16.merkle.MerkleSnapshotR\x0emerklesnapshot\x12#\n" +
	"\x05range\x18\x06 \x01(\v2\r.merkle.rangeR\x05range\"p\n" +
	"\bMetadata\x12\x1a\n" +
	"\bchecksum\x18\x01 \x01(\fR\bchecksum\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12.\n" +
	"\bnodeinfo\x18\x04 \x01(\v2\x12.nodeinfo.NodeInfoR\bnodeinfo\"\x86\x01\n" +
	"\x10PriorSyncMessage\x122\n" +
	"\tpriorsync\x18\x01 \x01(\v2\x14.priorsync.PriorSyncR\tpriorsync\x12\x1a\n" +
	"\x03ack\x18\x02 \x01(\v2\b.ack.AckR\x03ack\x12\"\n" +
	"\x05phase\x18\x03 \x01(\v2\f.phase.PhaseR\x05phase\"\xc8\x01\n" +
	"\rStreamMessage\x12<\n" +
	"\n" +
	"prior_sync\x18\x01 \x01(\v2\x1b.priorsync.PriorSyncMessageH\x00R\tpriorSync\x12/\n" +
	"\x06merkle\x18\x02 \x01(\v2\x15.merkle.MerkleMessageH\x00R\x06merkle\x12=\n" +
	"\n" +
	"merkle_req\x18\x03 \x01(\v2\x1c.merkle.MerkleRequestMessageH\x00R\tmerkleReqB\t\n" +
	"\apayloadBCZAgithub.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/priorsyncb\x06proto3"

var (
	file_priorsync_priorsync_proto_rawDescOnce sync.Once
	file_priorsync_priorsync_proto_rawDescData []byte
)

func file_priorsync_priorsync_proto_rawDescGZIP() []byte {
	file_priorsync_priorsync_proto_rawDescOnce.Do(func() {
		file_priorsync_priorsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_priorsync_priorsync_proto_rawDesc), len(file_priorsync_priorsync_proto_rawDesc)))
	})
	return file_priorsync_priorsync_proto_rawDescData
}

var file_priorsync_priorsync_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_priorsync_priorsync_proto_goTypes = []any{
	(*PriorSync)(nil),                   // 0: priorsync.PriorSync
	(*Metadata)(nil),                    // 1: priorsync.Metadata
	(*PriorSyncMessage)(nil),            // 2: priorsync.PriorSyncMessage
	(*StreamMessage)(nil),               // 3: priorsync.StreamMessage
	(*merkle.MerkleSnapshot)(nil),       // 4: merkle.MerkleSnapshot
	(*merkle.Range)(nil),                // 5: merkle.range
	(*nodeinfo.NodeInfo)(nil),           // 6: nodeinfo.NodeInfo
	(*ack.Ack)(nil),                     // 7: ack.Ack
	(*phase.Phase)(nil),                 // 8: phase.Phase
	(*merkle.MerkleMessage)(nil),        // 9: merkle.MerkleMessage
	(*merkle.MerkleRequestMessage)(nil), // 10: merkle.MerkleRequestMessage
}
var file_priorsync_priorsync_proto_depIdxs = []int32{
	1,  // 0: priorsync.PriorSync.metadata:type_name -> priorsync.Metadata
	4,  // 1: priorsync.PriorSync.merklesnapshot:type_name -> merkle.MerkleSnapshot
	5,  // 2: priorsync.PriorSync.range:type_name -> merkle.range
	6,  // 3: priorsync.Metadata.nodeinfo:type_name -> nodeinfo.NodeInfo
	0,  // 4: priorsync.PriorSyncMessage.priorsync:type_name -> priorsync.PriorSync
	7,  // 5: priorsync.PriorSyncMessage.ack:type_name -> ack.Ack
	8,  // 6: priorsync.PriorSyncMessage.phase:type_name -> phase.Phase
	2,  // 7: priorsync.StreamMessage.prior_sync:type_name -> priorsync.PriorSyncMessage
	9,  // 8: priorsync.StreamMessage.merkle:type_name -> merkle.MerkleMessage
	10, // 9: priorsync.StreamMessage.merkle_req:type_name -> merkle.MerkleRequestMessage
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_priorsync_priorsync_proto_init() }
func file_priorsync_priorsync_proto_init() {
	if File_priorsync_priorsync_proto != nil {
		return
	}
	file_priorsync_priorsync_proto_msgTypes[3].OneofWrappers = []any{
		(*StreamMessage_PriorSync)(nil),
		(*StreamMessage_Merkle)(nil),
		(*StreamMessage_MerkleReq)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_priorsync_priorsync_proto_rawDesc), len(file_priorsync_priorsync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_priorsync_priorsync_proto_goTypes,
		DependencyIndexes: file_priorsync_priorsync_proto_depIdxs,
		MessageInfos:      file_priorsync_priorsync_proto_msgTypes,
	}.Build()
	File_priorsync_priorsync_proto = out.File
	file_priorsync_priorsync_proto_goTypes = nil
	file_priorsync_priorsync_proto_depIdxs = nil
}
