// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: phase/phase.proto

package phase

import (
	auth "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/availability/auth"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phase struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PresentPhase    string                 `protobuf:"bytes,1,opt,name=present_phase,json=presentPhase,proto3" json:"present_phase,omitempty"`
	SuccessivePhase string                 `protobuf:"bytes,2,opt,name=successive_phase,json=successivePhase,proto3" json:"successive_phase,omitempty"`
	Success         bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"` // True if request is valid/accepted
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`      // Reason if success is false
	Auth            *auth.Auth             `protobuf:"bytes,6,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Phase) Reset() {
	*x = Phase{}
	mi := &file_phase_phase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Phase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phase) ProtoMessage() {}

func (x *Phase) ProtoReflect() protoreflect.Message {
	mi := &file_phase_phase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phase.ProtoReflect.Descriptor instead.
func (*Phase) Descriptor() ([]byte, []int) {
	return file_phase_phase_proto_rawDescGZIP(), []int{0}
}

func (x *Phase) GetPresentPhase() string {
	if x != nil {
		return x.PresentPhase
	}
	return ""
}

func (x *Phase) GetSuccessivePhase() string {
	if x != nil {
		return x.SuccessivePhase
	}
	return ""
}

func (x *Phase) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Phase) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Phase) GetAuth() *auth.Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

var File_phase_phase_proto protoreflect.FileDescriptor

const file_phase_phase_proto_rawDesc = "" +
	"\n" +
	"\x11phase/phase.proto\x12\x05phase\x1a\x1cavailability/auth/auth.proto\"\xa7\x01\n" +
	"\x05Phase\x12#\n" +
	"\rpresent_phase\x18\x01 \x01(\tR\fpresentPhase\x12)\n" +
	"\x10successive_phase\x18\x02 \x01(\tR\x0fsuccessivePhase\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1e\n" +
	"\x04auth\x18\x06 \x01(\v2\n" +
	".auth.AuthR\x04authB=Z;github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/phaseb\x06proto3"

var (
	file_phase_phase_proto_rawDescOnce sync.Once
	file_phase_phase_proto_rawDescData []byte
)

func file_phase_phase_proto_rawDescGZIP() []byte {
	file_phase_phase_proto_rawDescOnce.Do(func() {
		file_phase_phase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_phase_phase_proto_rawDesc), len(file_phase_phase_proto_rawDesc)))
	})
	return file_phase_phase_proto_rawDescData
}

var file_phase_phase_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_phase_phase_proto_goTypes = []any{
	(*Phase)(nil),     // 0: phase.Phase
	(*auth.Auth)(nil), // 1: auth.Auth
}
var file_phase_phase_proto_depIdxs = []int32{
	1, // 0: phase.Phase.auth:type_name -> auth.Auth
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_phase_phase_proto_init() }
func file_phase_phase_proto_init() {
	if File_phase_phase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_phase_phase_proto_rawDesc), len(file_phase_phase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_phase_phase_proto_goTypes,
		DependencyIndexes: file_phase_phase_proto_depIdxs,
		MessageInfos:      file_phase_phase_proto_msgTypes,
	}.Build()
	File_phase_phase_proto = out.File
	file_phase_phase_proto_goTypes = nil
	file_phase_phase_proto_depIdxs = nil
}
