// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: checksum/checksum.proto

package checksum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChecksumVersion mirrors the version constants in internal/checksum/checksum.go.
//
//	CRC32  (1) — 4-byte big-endian IEEE CRC32 digest.
//	SHA256 (2) — 32-byte SHA-256 digest.
type ChecksumVersion int32

const (
	ChecksumVersion_CHECKSUM_VERSION_UNSPECIFIED ChecksumVersion = 0
	ChecksumVersion_CRC32                        ChecksumVersion = 1
	ChecksumVersion_SHA256                       ChecksumVersion = 2
)

// Enum value maps for ChecksumVersion.
var (
	ChecksumVersion_name = map[int32]string{
		0: "CHECKSUM_VERSION_UNSPECIFIED",
		1: "CRC32",
		2: "SHA256",
	}
	ChecksumVersion_value = map[string]int32{
		"CHECKSUM_VERSION_UNSPECIFIED": 0,
		"CRC32":                        1,
		"SHA256":                       2,
	}
)

func (x ChecksumVersion) Enum() *ChecksumVersion {
	p := new(ChecksumVersion)
	*p = x
	return p
}

func (x ChecksumVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChecksumVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_checksum_checksum_proto_enumTypes[0].Descriptor()
}

func (ChecksumVersion) Type() protoreflect.EnumType {
	return &file_checksum_checksum_proto_enumTypes[0]
}

func (x ChecksumVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChecksumVersion.Descriptor instead.
func (ChecksumVersion) EnumDescriptor() ([]byte, []int) {
	return file_checksum_checksum_proto_rawDescGZIP(), []int{0}
}

// Checksum carries a versioned integrity digest over an arbitrary byte payload.
// The digest bytes are big-endian for CRC32 (4 bytes) and raw for SHA256 (32 bytes).
type Checksum struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// value is the raw digest bytes produced by internal/checksum.Create().
	Checksum      []byte          `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Version       ChecksumVersion `protobuf:"varint,2,opt,name=version,proto3,enum=checksum.ChecksumVersion" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checksum) Reset() {
	*x = Checksum{}
	mi := &file_checksum_checksum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checksum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checksum) ProtoMessage() {}

func (x *Checksum) ProtoReflect() protoreflect.Message {
	mi := &file_checksum_checksum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checksum.ProtoReflect.Descriptor instead.
func (*Checksum) Descriptor() ([]byte, []int) {
	return file_checksum_checksum_proto_rawDescGZIP(), []int{0}
}

func (x *Checksum) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *Checksum) GetVersion() ChecksumVersion {
	if x != nil {
		return x.Version
	}
	return ChecksumVersion_CHECKSUM_VERSION_UNSPECIFIED
}

var File_checksum_checksum_proto protoreflect.FileDescriptor

const file_checksum_checksum_proto_rawDesc = "" +
	"\n" +
	"\x17checksum/checksum.proto\x12\bchecksum\"[\n" +
	"\bChecksum\x12\x1a\n" +
	"\bchecksum\x18\x01 \x01(\fR\bchecksum\x123\n" +
	"\aversion\x18\x02 \x01(\x0e2\x19.checksum.ChecksumVersionR\aversion*J\n" +
	"\x0fChecksumVersion\x12 \n" +
	"\x1cCHECKSUM_VERSION_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05CRC32\x10\x01\x12\n" +
	"\n" +
	"\x06SHA256\x10\x02B@Z>github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/checksumb\x06proto3"

var (
	file_checksum_checksum_proto_rawDescOnce sync.Once
	file_checksum_checksum_proto_rawDescData []byte
)

func file_checksum_checksum_proto_rawDescGZIP() []byte {
	file_checksum_checksum_proto_rawDescOnce.Do(func() {
		file_checksum_checksum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checksum_checksum_proto_rawDesc), len(file_checksum_checksum_proto_rawDesc)))
	})
	return file_checksum_checksum_proto_rawDescData
}

var file_checksum_checksum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_checksum_checksum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_checksum_checksum_proto_goTypes = []any{
	(ChecksumVersion)(0), // 0: checksum.ChecksumVersion
	(*Checksum)(nil),     // 1: checksum.Checksum
}
var file_checksum_checksum_proto_depIdxs = []int32{
	0, // 0: checksum.Checksum.version:type_name -> checksum.ChecksumVersion
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_checksum_checksum_proto_init() }
func file_checksum_checksum_proto_init() {
	if File_checksum_checksum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checksum_checksum_proto_rawDesc), len(file_checksum_checksum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_checksum_checksum_proto_goTypes,
		DependencyIndexes: file_checksum_checksum_proto_depIdxs,
		EnumInfos:         file_checksum_checksum_proto_enumTypes,
		MessageInfos:      file_checksum_checksum_proto_msgTypes,
	}.Build()
	File_checksum_checksum_proto = out.File
	file_checksum_checksum_proto_goTypes = nil
	file_checksum_checksum_proto_depIdxs = nil
}
