// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: priorsync/priorsync.proto

package priorsync

import (
	ack "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/ack"
	headersync "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/headersync"
	merkle "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/merkle"
	nodeinfo "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/nodeinfo"
	phase "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/phase"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriorSync struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Blocknumber    uint64                 `protobuf:"varint,1,opt,name=blocknumber,proto3" json:"blocknumber,omitempty"`
	Stateroot      []byte                 `protobuf:"bytes,2,opt,name=stateroot,proto3" json:"stateroot,omitempty"`
	Blockhash      []byte                 `protobuf:"bytes,3,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	Metadata       *Metadata              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Merklesnapshot *merkle.MerkleSnapshot `protobuf:"bytes,5,opt,name=merklesnapshot,proto3" json:"merklesnapshot,omitempty"`
	Range          *merkle.Range          `protobuf:"bytes,6,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PriorSync) Reset() {
	*x = PriorSync{}
	mi := &file_priorsync_priorsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorSync) ProtoMessage() {}

func (x *PriorSync) ProtoReflect() protoreflect.Message {
	mi := &file_priorsync_priorsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorSync.ProtoReflect.Descriptor instead.
func (*PriorSync) Descriptor() ([]byte, []int) {
	return file_priorsync_priorsync_proto_rawDescGZIP(), []int{0}
}

func (x *PriorSync) GetBlocknumber() uint64 {
	if x != nil {
		return x.Blocknumber
	}
	return 0
}

func (x *PriorSync) GetStateroot() []byte {
	if x != nil {
		return x.Stateroot
	}
	return nil
}

func (x *PriorSync) GetBlockhash() []byte {
	if x != nil {
		return x.Blockhash
	}
	return nil
}

func (x *PriorSync) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PriorSync) GetMerklesnapshot() *merkle.MerkleSnapshot {
	if x != nil {
		return x.Merklesnapshot
	}
	return nil
}

func (x *PriorSync) GetRange() *merkle.Range {
	if x != nil {
		return x.Range
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksum      []byte                 `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Nodeinfo      *nodeinfo.NodeInfo     `protobuf:"bytes,4,opt,name=nodeinfo,proto3" json:"nodeinfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_priorsync_priorsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_priorsync_priorsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_priorsync_priorsync_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *Metadata) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Metadata) GetNodeinfo() *nodeinfo.NodeInfo {
	if x != nil {
		return x.Nodeinfo
	}
	return nil
}

type PriorSyncMessage struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Priorsync     *PriorSync                    `protobuf:"bytes,1,opt,name=priorsync,proto3" json:"priorsync,omitempty"`
	Ack           *ack.Ack                      `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`
	Phase         *phase.Phase                  `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Headersync    *headersync.HeaderSyncRequest `protobuf:"bytes,4,opt,name=headersync,proto3" json:"headersync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorSyncMessage) Reset() {
	*x = PriorSyncMessage{}
	mi := &file_priorsync_priorsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorSyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorSyncMessage) ProtoMessage() {}

func (x *PriorSyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_priorsync_priorsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorSyncMessage.ProtoReflect.Descriptor instead.
func (*PriorSyncMessage) Descriptor() ([]byte, []int) {
	return file_priorsync_priorsync_proto_rawDescGZIP(), []int{2}
}

func (x *PriorSyncMessage) GetPriorsync() *PriorSync {
	if x != nil {
		return x.Priorsync
	}
	return nil
}

func (x *PriorSyncMessage) GetAck() *ack.Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *PriorSyncMessage) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

func (x *PriorSyncMessage) GetHeadersync() *headersync.HeaderSyncRequest {
	if x != nil {
		return x.Headersync
	}
	return nil
}

// Heartbeat is sent periodically by Node 1 during computation to keep the stream alive.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix nanoseconds — for observability only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_priorsync_priorsync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_priorsync_priorsync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_priorsync_priorsync_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// StreamMessage is the wire envelope for the PriorSync stream.
// Node 1 sends N heartbeats followed by exactly one final response.
type StreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamMessage_Heartbeat
	//	*StreamMessage_Response
	Payload       isStreamMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_priorsync_priorsync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_priorsync_priorsync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_priorsync_priorsync_proto_rawDescGZIP(), []int{4}
}

func (x *StreamMessage) GetPayload() isStreamMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *StreamMessage) GetResponse() *PriorSyncMessage {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isStreamMessage_Payload interface {
	isStreamMessage_Payload()
}

type StreamMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type StreamMessage_Response struct {
	Response *PriorSyncMessage `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*StreamMessage_Heartbeat) isStreamMessage_Payload() {}

func (*StreamMessage_Response) isStreamMessage_Payload() {}

var File_priorsync_priorsync_proto protoreflect.FileDescriptor

const file_priorsync_priorsync_proto_rawDesc = "" +
	"\n" +
	"\x19priorsync/priorsync.proto\x12\tpriorsync\x1a\x17nodeinfo/nodeinfo.proto\x1a\rack/ack.proto\x1a\x11phase/phase.proto\x1a\x13merkle/merkle.proto\x1a\x1bheadersync/headersync.proto\"\xff\x01\n" +
	"\tPriorSync\x12 \n" +
	"\vblocknumber\x18\x01 \x01(\x04R\vblocknumber\x12\x1c\n" +
	"\tstateroot\x18\x02 \x01(\fR\tstateroot\x12\x1c\n" +
	"\tblockhash\x18\x03 \x01(\fR\tblockhash\x12/\n" +
	"\bmetadata\x18\x04 \x01(\v2\x13.priorsync.MetadataR\bmetadata\x12>\n" +
	"\x0emerklesnapshot\x18\x05 \x01(\v2\x16.merkle.MerkleSnapshotR\x0emerklesnapshot\x12#\n" +
	"\x05range\x18\x06 \x01(\v2\r.merkle.rangeR\x05range\"p\n" +
	"\bMetadata\x12\x1a\n" +
	"\bchecksum\x18\x01 \x01(\fR\bchecksum\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12.\n" +
	"\bnodeinfo\x18\x04 \x01(\v2\x12.nodeinfo.NodeInfoR\bnodeinfo\"\xc5\x01\n" +
	"\x10PriorSyncMessage\x122\n" +
	"\tpriorsync\x18\x01 \x01(\v2\x14.priorsync.PriorSyncR\tpriorsync\x12\x1a\n" +
	"\x03ack\x18\x02 \x01(\v2\b.ack.AckR\x03ack\x12\"\n" +
	"\x05phase\x18\x03 \x01(\v2\f.phase.PhaseR\x05phase\x12=\n" +
	"\n" +
	"headersync\x18\x04 \x01(\v2\x1d.headersync.HeaderSyncRequestR\n" +
	"headersync\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\x8b\x01\n" +
	"\rStreamMessage\x124\n" +
	"\theartbeat\x18\x01 \x01(\v2\x14.priorsync.HeartbeatH\x00R\theartbeat\x129\n" +
	"\bresponse\x18\x02 \x01(\v2\x1b.priorsync.PriorSyncMessageH\x00R\bresponseB\t\n" +
	"\apayloadBAZ?github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/priorsyncb\x06proto3"

var (
	file_priorsync_priorsync_proto_rawDescOnce sync.Once
	file_priorsync_priorsync_proto_rawDescData []byte
)

func file_priorsync_priorsync_proto_rawDescGZIP() []byte {
	file_priorsync_priorsync_proto_rawDescOnce.Do(func() {
		file_priorsync_priorsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_priorsync_priorsync_proto_rawDesc), len(file_priorsync_priorsync_proto_rawDesc)))
	})
	return file_priorsync_priorsync_proto_rawDescData
}

var file_priorsync_priorsync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_priorsync_priorsync_proto_goTypes = []any{
	(*PriorSync)(nil),                    // 0: priorsync.PriorSync
	(*Metadata)(nil),                     // 1: priorsync.Metadata
	(*PriorSyncMessage)(nil),             // 2: priorsync.PriorSyncMessage
	(*Heartbeat)(nil),                    // 3: priorsync.Heartbeat
	(*StreamMessage)(nil),                // 4: priorsync.StreamMessage
	(*merkle.MerkleSnapshot)(nil),        // 5: merkle.MerkleSnapshot
	(*merkle.Range)(nil),                 // 6: merkle.range
	(*nodeinfo.NodeInfo)(nil),            // 7: nodeinfo.NodeInfo
	(*ack.Ack)(nil),                      // 8: ack.Ack
	(*phase.Phase)(nil),                  // 9: phase.Phase
	(*headersync.HeaderSyncRequest)(nil), // 10: headersync.HeaderSyncRequest
}
var file_priorsync_priorsync_proto_depIdxs = []int32{
	1,  // 0: priorsync.PriorSync.metadata:type_name -> priorsync.Metadata
	5,  // 1: priorsync.PriorSync.merklesnapshot:type_name -> merkle.MerkleSnapshot
	6,  // 2: priorsync.PriorSync.range:type_name -> merkle.range
	7,  // 3: priorsync.Metadata.nodeinfo:type_name -> nodeinfo.NodeInfo
	0,  // 4: priorsync.PriorSyncMessage.priorsync:type_name -> priorsync.PriorSync
	8,  // 5: priorsync.PriorSyncMessage.ack:type_name -> ack.Ack
	9,  // 6: priorsync.PriorSyncMessage.phase:type_name -> phase.Phase
	10, // 7: priorsync.PriorSyncMessage.headersync:type_name -> headersync.HeaderSyncRequest
	3,  // 8: priorsync.StreamMessage.heartbeat:type_name -> priorsync.Heartbeat
	2,  // 9: priorsync.StreamMessage.response:type_name -> priorsync.PriorSyncMessage
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_priorsync_priorsync_proto_init() }
func file_priorsync_priorsync_proto_init() {
	if File_priorsync_priorsync_proto != nil {
		return
	}
	file_priorsync_priorsync_proto_msgTypes[4].OneofWrappers = []any{
		(*StreamMessage_Heartbeat)(nil),
		(*StreamMessage_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_priorsync_priorsync_proto_rawDesc), len(file_priorsync_priorsync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_priorsync_priorsync_proto_goTypes,
		DependencyIndexes: file_priorsync_priorsync_proto_depIdxs,
		MessageInfos:      file_priorsync_priorsync_proto_msgTypes,
	}.Build()
	File_priorsync_priorsync_proto = out.File
	file_priorsync_priorsync_proto_goTypes = nil
	file_priorsync_priorsync_proto_depIdxs = nil
}
