// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: pots/pots.proto

package pots

import (
	phase "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/phase"
	tagging "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/tagging"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// pots request message
// - map{blocknumber: blockhash}
// - pots_timestamp
// - Auth
type PoTSRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Blocks            map[uint64][]byte      `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LatestBlockNumber uint64                 `protobuf:"varint,2,opt,name=latest_block_number,json=latestBlockNumber,proto3" json:"latest_block_number,omitempty"`
	Phase             *phase.Phase           `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PoTSRequest) Reset() {
	*x = PoTSRequest{}
	mi := &file_pots_pots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoTSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoTSRequest) ProtoMessage() {}

func (x *PoTSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pots_pots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoTSRequest.ProtoReflect.Descriptor instead.
func (*PoTSRequest) Descriptor() ([]byte, []int) {
	return file_pots_pots_proto_rawDescGZIP(), []int{0}
}

func (x *PoTSRequest) GetBlocks() map[uint64][]byte {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *PoTSRequest) GetLatestBlockNumber() uint64 {
	if x != nil {
		return x.LatestBlockNumber
	}
	return 0
}

func (x *PoTSRequest) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

// This response have the tags of blocks which are missing in the map and beyond that timestamp
// for example if 20 blocks is synced after that timestamp, and the map have 18 blocks remaining 2 blocks would be sent in tagging.
// then that tagging will be given to headersync and data sync eventually.
type PoTSResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tag               *tagging.Tag           `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	LatestBlockNumber uint64                 `protobuf:"varint,2,opt,name=latest_block_number,json=latestBlockNumber,proto3" json:"latest_block_number,omitempty"` // Optional: server's latest known block
	Phase             *phase.Phase           `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PoTSResponse) Reset() {
	*x = PoTSResponse{}
	mi := &file_pots_pots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoTSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoTSResponse) ProtoMessage() {}

func (x *PoTSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pots_pots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoTSResponse.ProtoReflect.Descriptor instead.
func (*PoTSResponse) Descriptor() ([]byte, []int) {
	return file_pots_pots_proto_rawDescGZIP(), []int{1}
}

func (x *PoTSResponse) GetTag() *tagging.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *PoTSResponse) GetLatestBlockNumber() uint64 {
	if x != nil {
		return x.LatestBlockNumber
	}
	return 0
}

func (x *PoTSResponse) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

// Heartbeat is sent periodically by Node 1 during computation to keep the stream alive.
type PoTSHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix nanoseconds — for observability only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoTSHeartbeat) Reset() {
	*x = PoTSHeartbeat{}
	mi := &file_pots_pots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoTSHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoTSHeartbeat) ProtoMessage() {}

func (x *PoTSHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pots_pots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoTSHeartbeat.ProtoReflect.Descriptor instead.
func (*PoTSHeartbeat) Descriptor() ([]byte, []int) {
	return file_pots_pots_proto_rawDescGZIP(), []int{2}
}

func (x *PoTSHeartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PoTSStreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PoTSStreamMessage_Response
	//	*PoTSStreamMessage_Heartbeat
	Payload       isPoTSStreamMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoTSStreamMessage) Reset() {
	*x = PoTSStreamMessage{}
	mi := &file_pots_pots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoTSStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoTSStreamMessage) ProtoMessage() {}

func (x *PoTSStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pots_pots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoTSStreamMessage.ProtoReflect.Descriptor instead.
func (*PoTSStreamMessage) Descriptor() ([]byte, []int) {
	return file_pots_pots_proto_rawDescGZIP(), []int{3}
}

func (x *PoTSStreamMessage) GetPayload() isPoTSStreamMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PoTSStreamMessage) GetResponse() *PoTSResponse {
	if x != nil {
		if x, ok := x.Payload.(*PoTSStreamMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *PoTSStreamMessage) GetHeartbeat() *PoTSHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*PoTSStreamMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isPoTSStreamMessage_Payload interface {
	isPoTSStreamMessage_Payload()
}

type PoTSStreamMessage_Response struct {
	Response *PoTSResponse `protobuf:"bytes,1,opt,name=response,proto3,oneof"`
}

type PoTSStreamMessage_Heartbeat struct {
	Heartbeat *PoTSHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*PoTSStreamMessage_Response) isPoTSStreamMessage_Payload() {}

func (*PoTSStreamMessage_Heartbeat) isPoTSStreamMessage_Payload() {}

var File_pots_pots_proto protoreflect.FileDescriptor

const file_pots_pots_proto_rawDesc = "" +
	"\n" +
	"\x0fpots/pots.proto\x12\x04pots\x1a\x11tagging/tag.proto\x1a\x11phase/phase.proto\"\xd3\x01\n" +
	"\vPoTSRequest\x125\n" +
	"\x06blocks\x18\x01 \x03(\v2\x1d.pots.PoTSRequest.BlocksEntryR\x06blocks\x12.\n" +
	"\x13latest_block_number\x18\x02 \x01(\x04R\x11latestBlockNumber\x12\"\n" +
	"\x05phase\x18\x03 \x01(\v2\f.phase.PhaseR\x05phase\x1a9\n" +
	"\vBlocksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x82\x01\n" +
	"\fPoTSResponse\x12\x1e\n" +
	"\x03tag\x18\x01 \x01(\v2\f.tagging.TagR\x03tag\x12.\n" +
	"\x13latest_block_number\x18\x02 \x01(\x04R\x11latestBlockNumber\x12\"\n" +
	"\x05phase\x18\x03 \x01(\v2\f.phase.PhaseR\x05phase\"-\n" +
	"\rPoTSHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\x85\x01\n" +
	"\x11PoTSStreamMessage\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x12.pots.PoTSResponseH\x00R\bresponse\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x13.pots.PoTSHeartbeatH\x00R\theartbeatB\t\n" +
	"\apayloadB<Z:github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/potsb\x06proto3"

var (
	file_pots_pots_proto_rawDescOnce sync.Once
	file_pots_pots_proto_rawDescData []byte
)

func file_pots_pots_proto_rawDescGZIP() []byte {
	file_pots_pots_proto_rawDescOnce.Do(func() {
		file_pots_pots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pots_pots_proto_rawDesc), len(file_pots_pots_proto_rawDesc)))
	})
	return file_pots_pots_proto_rawDescData
}

var file_pots_pots_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pots_pots_proto_goTypes = []any{
	(*PoTSRequest)(nil),       // 0: pots.PoTSRequest
	(*PoTSResponse)(nil),      // 1: pots.PoTSResponse
	(*PoTSHeartbeat)(nil),     // 2: pots.PoTSHeartbeat
	(*PoTSStreamMessage)(nil), // 3: pots.PoTSStreamMessage
	nil,                       // 4: pots.PoTSRequest.BlocksEntry
	(*phase.Phase)(nil),       // 5: phase.Phase
	(*tagging.Tag)(nil),       // 6: tagging.Tag
}
var file_pots_pots_proto_depIdxs = []int32{
	4, // 0: pots.PoTSRequest.blocks:type_name -> pots.PoTSRequest.BlocksEntry
	5, // 1: pots.PoTSRequest.phase:type_name -> phase.Phase
	6, // 2: pots.PoTSResponse.tag:type_name -> tagging.Tag
	5, // 3: pots.PoTSResponse.phase:type_name -> phase.Phase
	1, // 4: pots.PoTSStreamMessage.response:type_name -> pots.PoTSResponse
	2, // 5: pots.PoTSStreamMessage.heartbeat:type_name -> pots.PoTSHeartbeat
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pots_pots_proto_init() }
func file_pots_pots_proto_init() {
	if File_pots_pots_proto != nil {
		return
	}
	file_pots_pots_proto_msgTypes[3].OneofWrappers = []any{
		(*PoTSStreamMessage_Response)(nil),
		(*PoTSStreamMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pots_pots_proto_rawDesc), len(file_pots_pots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pots_pots_proto_goTypes,
		DependencyIndexes: file_pots_pots_proto_depIdxs,
		MessageInfos:      file_pots_pots_proto_msgTypes,
	}.Build()
	File_pots_pots_proto = out.File
	file_pots_pots_proto_goTypes = nil
	file_pots_pots_proto_depIdxs = nil
}
