// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: pots/pots.proto

package pots

import (
	auth "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/availability/auth"
	tagging "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/tagging"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// pots request message
// - map{blocknumber: blockhash}
// - pots_timestamp
// - Auth
type PoTSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        map[uint64][]byte      `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PotsTimestamp uint64                 `protobuf:"varint,2,opt,name=pots_timestamp,json=potsTimestamp,proto3" json:"pots_timestamp,omitempty"`
	Auth          *auth.Auth             `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoTSRequest) Reset() {
	*x = PoTSRequest{}
	mi := &file_pots_pots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoTSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoTSRequest) ProtoMessage() {}

func (x *PoTSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pots_pots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoTSRequest.ProtoReflect.Descriptor instead.
func (*PoTSRequest) Descriptor() ([]byte, []int) {
	return file_pots_pots_proto_rawDescGZIP(), []int{0}
}

func (x *PoTSRequest) GetBlocks() map[uint64][]byte {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *PoTSRequest) GetPotsTimestamp() uint64 {
	if x != nil {
		return x.PotsTimestamp
	}
	return 0
}

func (x *PoTSRequest) GetAuth() *auth.Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

// This response have the tags of blocks which are missing in the map and beyond that timestamp
// for example if 20 blocks is synced after that timestamp, and the map have 18 blocks remaining 2 blocks would be sent in tagging.
// then that tagging will be given to headersync and data sync eventually.
type PoTSResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Tag               *tagging.Tag           `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                   // Optional: for failure cases
	LatestBlockNumber uint64                 `protobuf:"varint,4,opt,name=latest_block_number,json=latestBlockNumber,proto3" json:"latest_block_number,omitempty"` // Optional: server's latest known block
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PoTSResponse) Reset() {
	*x = PoTSResponse{}
	mi := &file_pots_pots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoTSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoTSResponse) ProtoMessage() {}

func (x *PoTSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pots_pots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoTSResponse.ProtoReflect.Descriptor instead.
func (*PoTSResponse) Descriptor() ([]byte, []int) {
	return file_pots_pots_proto_rawDescGZIP(), []int{1}
}

func (x *PoTSResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PoTSResponse) GetTag() *tagging.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *PoTSResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PoTSResponse) GetLatestBlockNumber() uint64 {
	if x != nil {
		return x.LatestBlockNumber
	}
	return 0
}

var File_pots_pots_proto protoreflect.FileDescriptor

const file_pots_pots_proto_rawDesc = "" +
	"\n" +
	"\x0fpots/pots.proto\x12\x04pots\x1a\x1cavailability/auth/auth.proto\x1a\x11tagging/tag.proto\"\xc6\x01\n" +
	"\vPoTSRequest\x125\n" +
	"\x06blocks\x18\x01 \x03(\v2\x1d.pots.PoTSRequest.BlocksEntryR\x06blocks\x12%\n" +
	"\x0epots_timestamp\x18\x02 \x01(\x04R\rpotsTimestamp\x12\x1e\n" +
	"\x04auth\x18\x03 \x01(\v2\n" +
	".auth.AuthR\x04auth\x1a9\n" +
	"\vBlocksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x9d\x01\n" +
	"\fPoTSResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1e\n" +
	"\x03tag\x18\x02 \x01(\v2\f.tagging.TagR\x03tag\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12.\n" +
	"\x13latest_block_number\x18\x04 \x01(\x04R\x11latestBlockNumberB<Z:github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/potsb\x06proto3"

var (
	file_pots_pots_proto_rawDescOnce sync.Once
	file_pots_pots_proto_rawDescData []byte
)

func file_pots_pots_proto_rawDescGZIP() []byte {
	file_pots_pots_proto_rawDescOnce.Do(func() {
		file_pots_pots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pots_pots_proto_rawDesc), len(file_pots_pots_proto_rawDesc)))
	})
	return file_pots_pots_proto_rawDescData
}

var file_pots_pots_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pots_pots_proto_goTypes = []any{
	(*PoTSRequest)(nil),  // 0: pots.PoTSRequest
	(*PoTSResponse)(nil), // 1: pots.PoTSResponse
	nil,                  // 2: pots.PoTSRequest.BlocksEntry
	(*auth.Auth)(nil),    // 3: auth.Auth
	(*tagging.Tag)(nil),  // 4: tagging.Tag
}
var file_pots_pots_proto_depIdxs = []int32{
	2, // 0: pots.PoTSRequest.blocks:type_name -> pots.PoTSRequest.BlocksEntry
	3, // 1: pots.PoTSRequest.auth:type_name -> auth.Auth
	4, // 2: pots.PoTSResponse.tag:type_name -> tagging.Tag
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pots_pots_proto_init() }
func file_pots_pots_proto_init() {
	if File_pots_pots_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pots_pots_proto_rawDesc), len(file_pots_pots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pots_pots_proto_goTypes,
		DependencyIndexes: file_pots_pots_proto_depIdxs,
		MessageInfos:      file_pots_pots_proto_msgTypes,
	}.Build()
	File_pots_pots_proto = out.File
	file_pots_pots_proto_goTypes = nil
	file_pots_pots_proto_depIdxs = nil
}
