// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: availability/availability.proto

package availability

import (
	auth "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/availability/auth"
	merkle "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/merkle"
	nodeinfo "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/nodeinfo"
	phase "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/phase"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *merkle.Range          `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityRequest) Reset() {
	*x = AvailabilityRequest{}
	mi := &file_availability_availability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityRequest) ProtoMessage() {}

func (x *AvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availability_availability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityRequest.ProtoReflect.Descriptor instead.
func (*AvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_availability_availability_proto_rawDescGZIP(), []int{0}
}

func (x *AvailabilityRequest) GetRange() *merkle.Range {
	if x != nil {
		return x.Range
	}
	return nil
}

type AvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	Nodeinfo      *nodeinfo.NodeInfo     `protobuf:"bytes,2,opt,name=nodeinfo,proto3" json:"nodeinfo,omitempty"`
	BlockMerge    uint32                 `protobuf:"varint,3,opt,name=block_merge,json=blockMerge,proto3" json:"block_merge,omitempty"`
	Auth          *auth.Auth             `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	Phase         *phase.Phase           `protobuf:"bytes,5,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityResponse) Reset() {
	*x = AvailabilityResponse{}
	mi := &file_availability_availability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityResponse) ProtoMessage() {}

func (x *AvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availability_availability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityResponse.ProtoReflect.Descriptor instead.
func (*AvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_availability_availability_proto_rawDescGZIP(), []int{1}
}

func (x *AvailabilityResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *AvailabilityResponse) GetNodeinfo() *nodeinfo.NodeInfo {
	if x != nil {
		return x.Nodeinfo
	}
	return nil
}

func (x *AvailabilityResponse) GetBlockMerge() uint32 {
	if x != nil {
		return x.BlockMerge
	}
	return 0
}

func (x *AvailabilityResponse) GetAuth() *auth.Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *AvailabilityResponse) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

var File_availability_availability_proto protoreflect.FileDescriptor

const file_availability_availability_proto_rawDesc = "" +
	"\n" +
	"\x1favailability/availability.proto\x12\favailability\x1a\x11phase/phase.proto\x1a\x13merkle/merkle.proto\x1a\x1cavailability/auth/auth.proto\x1a\x17nodeinfo/nodeinfo.proto\":\n" +
	"\x13AvailabilityRequest\x12#\n" +
	"\x05range\x18\x02 \x01(\v2\r.merkle.rangeR\x05range\"\xce\x01\n" +
	"\x14AvailabilityResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable\x12.\n" +
	"\bnodeinfo\x18\x02 \x01(\v2\x12.nodeinfo.NodeInfoR\bnodeinfo\x12\x1f\n" +
	"\vblock_merge\x18\x03 \x01(\rR\n" +
	"blockMerge\x12\x1e\n" +
	"\x04auth\x18\x04 \x01(\v2\n" +
	".auth.AuthR\x04auth\x12\"\n" +
	"\x05phase\x18\x05 \x01(\v2\f.phase.PhaseR\x05phaseBDZBgithub.com/JupiterMetaLabs/JMDN-FastSync/common/proto/availabilityb\x06proto3"

var (
	file_availability_availability_proto_rawDescOnce sync.Once
	file_availability_availability_proto_rawDescData []byte
)

func file_availability_availability_proto_rawDescGZIP() []byte {
	file_availability_availability_proto_rawDescOnce.Do(func() {
		file_availability_availability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_availability_availability_proto_rawDesc), len(file_availability_availability_proto_rawDesc)))
	})
	return file_availability_availability_proto_rawDescData
}

var file_availability_availability_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_availability_availability_proto_goTypes = []any{
	(*AvailabilityRequest)(nil),  // 0: availability.AvailabilityRequest
	(*AvailabilityResponse)(nil), // 1: availability.AvailabilityResponse
	(*merkle.Range)(nil),         // 2: merkle.range
	(*nodeinfo.NodeInfo)(nil),    // 3: nodeinfo.NodeInfo
	(*auth.Auth)(nil),            // 4: auth.Auth
	(*phase.Phase)(nil),          // 5: phase.Phase
}
var file_availability_availability_proto_depIdxs = []int32{
	2, // 0: availability.AvailabilityRequest.range:type_name -> merkle.range
	3, // 1: availability.AvailabilityResponse.nodeinfo:type_name -> nodeinfo.NodeInfo
	4, // 2: availability.AvailabilityResponse.auth:type_name -> auth.Auth
	5, // 3: availability.AvailabilityResponse.phase:type_name -> phase.Phase
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_availability_availability_proto_init() }
func file_availability_availability_proto_init() {
	if File_availability_availability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_availability_availability_proto_rawDesc), len(file_availability_availability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_availability_availability_proto_goTypes,
		DependencyIndexes: file_availability_availability_proto_depIdxs,
		MessageInfos:      file_availability_availability_proto_msgTypes,
	}.Build()
	File_availability_availability_proto = out.File
	file_availability_availability_proto_goTypes = nil
	file_availability_availability_proto_depIdxs = nil
}
