// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: nodeinfo/nodeinfo.proto

package nodeinfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Multiaddrs    [][]byte               `protobuf:"bytes,2,rep,name=multiaddrs,proto3" json:"multiaddrs,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Version       uint32                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_nodeinfo_nodeinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nodeinfo_nodeinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_nodeinfo_nodeinfo_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *NodeInfo) GetMultiaddrs() [][]byte {
	if x != nil {
		return x.Multiaddrs
	}
	return nil
}

func (x *NodeInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *NodeInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *NodeInfo) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NodeInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

var File_nodeinfo_nodeinfo_proto protoreflect.FileDescriptor

const file_nodeinfo_nodeinfo_proto_rawDesc = "" +
	"\n" +
	"\x17nodeinfo/nodeinfo.proto\x12\bnodeinfo\"\xbc\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12\x1e\n" +
	"\n" +
	"multiaddrs\x18\x02 \x03(\fR\n" +
	"multiaddrs\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocolBBZ@github.com/JupiterMetaLabs/JMDN-FastSync/internal/proto/nodeinfob\x06proto3"

var (
	file_nodeinfo_nodeinfo_proto_rawDescOnce sync.Once
	file_nodeinfo_nodeinfo_proto_rawDescData []byte
)

func file_nodeinfo_nodeinfo_proto_rawDescGZIP() []byte {
	file_nodeinfo_nodeinfo_proto_rawDescOnce.Do(func() {
		file_nodeinfo_nodeinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodeinfo_nodeinfo_proto_rawDesc), len(file_nodeinfo_nodeinfo_proto_rawDesc)))
	})
	return file_nodeinfo_nodeinfo_proto_rawDescData
}

var file_nodeinfo_nodeinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nodeinfo_nodeinfo_proto_goTypes = []any{
	(*NodeInfo)(nil), // 0: nodeinfo.NodeInfo
}
var file_nodeinfo_nodeinfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nodeinfo_nodeinfo_proto_init() }
func file_nodeinfo_nodeinfo_proto_init() {
	if File_nodeinfo_nodeinfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodeinfo_nodeinfo_proto_rawDesc), len(file_nodeinfo_nodeinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nodeinfo_nodeinfo_proto_goTypes,
		DependencyIndexes: file_nodeinfo_nodeinfo_proto_depIdxs,
		MessageInfos:      file_nodeinfo_nodeinfo_proto_msgTypes,
	}.Build()
	File_nodeinfo_nodeinfo_proto = out.File
	file_nodeinfo_nodeinfo_proto_goTypes = nil
	file_nodeinfo_nodeinfo_proto_depIdxs = nil
}
