// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: block/block_nonheader.proto

package block

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SnapshotRecord maps to the snapshots table (append-only, Create Read).
// FK -> blocks.block_number (one-to-one).
type SnapshotRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     []byte                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`  // CHAR(66) stored as raw bytes
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix nanoseconds (maps to TIMESTAMPTZ)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRecord) Reset() {
	*x = SnapshotRecord{}
	mi := &file_block_block_nonheader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRecord) ProtoMessage() {}

func (x *SnapshotRecord) ProtoReflect() protoreflect.Message {
	mi := &file_block_block_nonheader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRecord.ProtoReflect.Descriptor instead.
func (*SnapshotRecord) Descriptor() ([]byte, []int) {
	return file_block_block_nonheader_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotRecord) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *SnapshotRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ZKProof maps to the zk_proofs table (append-only, Create Read).
// FK -> blocks.block_number (one-proof-per-block).
type ZKProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProofHash     string                 `protobuf:"bytes,1,opt,name=proof_hash,json=proofHash,proto3" json:"proof_hash,omitempty"`    // CHAR(66) unique
	StarkProof    []byte                 `protobuf:"bytes,2,opt,name=stark_proof,json=starkProof,proto3" json:"stark_proof,omitempty"` // BYTEA NOT NULL
	Commitment    []byte                 `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment,omitempty"`                   // BYTEA nullable
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`   // Unix nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZKProof) Reset() {
	*x = ZKProof{}
	mi := &file_block_block_nonheader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZKProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZKProof) ProtoMessage() {}

func (x *ZKProof) ProtoReflect() protoreflect.Message {
	mi := &file_block_block_nonheader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZKProof.ProtoReflect.Descriptor instead.
func (*ZKProof) Descriptor() ([]byte, []int) {
	return file_block_block_nonheader_proto_rawDescGZIP(), []int{1}
}

func (x *ZKProof) GetProofHash() string {
	if x != nil {
		return x.ProofHash
	}
	return ""
}

func (x *ZKProof) GetStarkProof() []byte {
	if x != nil {
		return x.StarkProof
	}
	return nil
}

func (x *ZKProof) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *ZKProof) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// DBTransaction maps to the transactions table (append-only, Create Read).
// FK -> snapshots.block_number (snapshot owns the tx set).
// Uses block.Transaction for all core tx fields; adds only DB-specific extras.
type DBTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            *Transaction           `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`                                 // all core fields (hash, from, to, value, gas, sig, …)
	TxIndex       uint32                 `protobuf:"varint,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`       // SMALLINT — position within the block
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // TIMESTAMPTZ — Unix nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBTransaction) Reset() {
	*x = DBTransaction{}
	mi := &file_block_block_nonheader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBTransaction) ProtoMessage() {}

func (x *DBTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_block_block_nonheader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBTransaction.ProtoReflect.Descriptor instead.
func (*DBTransaction) Descriptor() ([]byte, []int) {
	return file_block_block_nonheader_proto_rawDescGZIP(), []int{2}
}

func (x *DBTransaction) GetTx() *Transaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *DBTransaction) GetTxIndex() uint32 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *DBTransaction) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// L1Finality maps to the l1_finality table (append-only, Create Read).
// Confirmation is the L1 anchor (e.g. settlement contract / tx hash).
type L1Finality struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmation  []byte                 `protobuf:"bytes,1,opt,name=confirmation,proto3" json:"confirmation,omitempty"`                             // CHAR(42) PK
	BlockNumbers  []uint64               `protobuf:"varint,2,rep,packed,name=block_numbers,json=blockNumbers,proto3" json:"block_numbers,omitempty"` // BIGINT[] NOT NULL
	Metadata      []byte                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`                                     // JSONB (serialized JSON bytes)
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                 // Unix nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L1Finality) Reset() {
	*x = L1Finality{}
	mi := &file_block_block_nonheader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L1Finality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L1Finality) ProtoMessage() {}

func (x *L1Finality) ProtoReflect() protoreflect.Message {
	mi := &file_block_block_nonheader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L1Finality.ProtoReflect.Descriptor instead.
func (*L1Finality) Descriptor() ([]byte, []int) {
	return file_block_block_nonheader_proto_rawDescGZIP(), []int{3}
}

func (x *L1Finality) GetConfirmation() []byte {
	if x != nil {
		return x.Confirmation
	}
	return nil
}

func (x *L1Finality) GetBlockNumbers() []uint64 {
	if x != nil {
		return x.BlockNumbers
	}
	return nil
}

func (x *L1Finality) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *L1Finality) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ================================================================
// NonHeaders — full block payload without blocks-table header fields
// (state_root, parent_hash, gas, timestamps are in the blocks table)
// BlockNumber is the shared PK/FK across all sub-tables.
// ================================================================
type NonHeaders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Snapshot      *SnapshotRecord        `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Transactions  []*DBTransaction       `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	ZkProof       *ZKProof               `protobuf:"bytes,4,opt,name=zk_proof,json=zkProof,proto3" json:"zk_proof,omitempty"`
	L1Finality    *L1Finality            `protobuf:"bytes,5,opt,name=l1_finality,json=l1Finality,proto3" json:"l1_finality,omitempty"` // empty/unset until finalised on L1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonHeaders) Reset() {
	*x = NonHeaders{}
	mi := &file_block_block_nonheader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonHeaders) ProtoMessage() {}

func (x *NonHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_block_block_nonheader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonHeaders.ProtoReflect.Descriptor instead.
func (*NonHeaders) Descriptor() ([]byte, []int) {
	return file_block_block_nonheader_proto_rawDescGZIP(), []int{4}
}

func (x *NonHeaders) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *NonHeaders) GetSnapshot() *SnapshotRecord {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *NonHeaders) GetTransactions() []*DBTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *NonHeaders) GetZkProof() *ZKProof {
	if x != nil {
		return x.ZkProof
	}
	return nil
}

func (x *NonHeaders) GetL1Finality() *L1Finality {
	if x != nil {
		return x.L1Finality
	}
	return nil
}

var File_block_block_nonheader_proto protoreflect.FileDescriptor

const file_block_block_nonheader_proto_rawDesc = "" +
	"\n" +
	"\x1bblock/block_nonheader.proto\x12\x05block\x1a\x11block/block.proto\"N\n" +
	"\x0eSnapshotRecord\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\"\x88\x01\n" +
	"\aZKProof\x12\x1d\n" +
	"\n" +
	"proof_hash\x18\x01 \x01(\tR\tproofHash\x12\x1f\n" +
	"\vstark_proof\x18\x02 \x01(\fR\n" +
	"starkProof\x12\x1e\n" +
	"\n" +
	"commitment\x18\x03 \x01(\fR\n" +
	"commitment\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"m\n" +
	"\rDBTransaction\x12\"\n" +
	"\x02tx\x18\x01 \x01(\v2\x12.block.TransactionR\x02tx\x12\x19\n" +
	"\btx_index\x18\x02 \x01(\rR\atxIndex\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"\x90\x01\n" +
	"\n" +
	"L1Finality\x12\"\n" +
	"\fconfirmation\x18\x01 \x01(\fR\fconfirmation\x12#\n" +
	"\rblock_numbers\x18\x02 \x03(\x04R\fblockNumbers\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\fR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\xfb\x01\n" +
	"\n" +
	"NonHeaders\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x121\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x15.block.SnapshotRecordR\bsnapshot\x128\n" +
	"\ftransactions\x18\x03 \x03(\v2\x14.block.DBTransactionR\ftransactions\x12)\n" +
	"\bzk_proof\x18\x04 \x01(\v2\x0e.block.ZKProofR\azkProof\x122\n" +
	"\vl1_finality\x18\x05 \x01(\v2\x11.block.L1FinalityR\n" +
	"l1FinalityB=Z;github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/blockb\x06proto3"

var (
	file_block_block_nonheader_proto_rawDescOnce sync.Once
	file_block_block_nonheader_proto_rawDescData []byte
)

func file_block_block_nonheader_proto_rawDescGZIP() []byte {
	file_block_block_nonheader_proto_rawDescOnce.Do(func() {
		file_block_block_nonheader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_block_nonheader_proto_rawDesc), len(file_block_block_nonheader_proto_rawDesc)))
	})
	return file_block_block_nonheader_proto_rawDescData
}

var file_block_block_nonheader_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_block_block_nonheader_proto_goTypes = []any{
	(*SnapshotRecord)(nil), // 0: block.SnapshotRecord
	(*ZKProof)(nil),        // 1: block.ZKProof
	(*DBTransaction)(nil),  // 2: block.DBTransaction
	(*L1Finality)(nil),     // 3: block.L1Finality
	(*NonHeaders)(nil),     // 4: block.NonHeaders
	(*Transaction)(nil),    // 5: block.Transaction
}
var file_block_block_nonheader_proto_depIdxs = []int32{
	5, // 0: block.DBTransaction.tx:type_name -> block.Transaction
	0, // 1: block.NonHeaders.snapshot:type_name -> block.SnapshotRecord
	2, // 2: block.NonHeaders.transactions:type_name -> block.DBTransaction
	1, // 3: block.NonHeaders.zk_proof:type_name -> block.ZKProof
	3, // 4: block.NonHeaders.l1_finality:type_name -> block.L1Finality
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_block_block_nonheader_proto_init() }
func file_block_block_nonheader_proto_init() {
	if File_block_block_nonheader_proto != nil {
		return
	}
	file_block_block_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_block_nonheader_proto_rawDesc), len(file_block_block_nonheader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_block_nonheader_proto_goTypes,
		DependencyIndexes: file_block_block_nonheader_proto_depIdxs,
		MessageInfos:      file_block_block_nonheader_proto_msgTypes,
	}.Build()
	File_block_block_nonheader_proto = out.File
	file_block_block_nonheader_proto_goTypes = nil
	file_block_block_nonheader_proto_depIdxs = nil
}
