// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: headersync/headersync.proto

package headersync

import (
	ack "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/ack"
	block "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/block"
	phase "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/phase"
	tagging "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/tagging"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeaderSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *tagging.Tag           `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Ack           *ack.Ack               `protobuf:"bytes,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Phase         *phase.Phase           `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderSyncRequest) Reset() {
	*x = HeaderSyncRequest{}
	mi := &file_headersync_headersync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderSyncRequest) ProtoMessage() {}

func (x *HeaderSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_headersync_headersync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderSyncRequest.ProtoReflect.Descriptor instead.
func (*HeaderSyncRequest) Descriptor() ([]byte, []int) {
	return file_headersync_headersync_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderSyncRequest) GetTag() *tagging.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *HeaderSyncRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HeaderSyncRequest) GetAck() *ack.Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *HeaderSyncRequest) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

type HeaderSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        []*block.Header        `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Ack           *ack.Ack               `protobuf:"bytes,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Phase         *phase.Phase           `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderSyncResponse) Reset() {
	*x = HeaderSyncResponse{}
	mi := &file_headersync_headersync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderSyncResponse) ProtoMessage() {}

func (x *HeaderSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_headersync_headersync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderSyncResponse.ProtoReflect.Descriptor instead.
func (*HeaderSyncResponse) Descriptor() ([]byte, []int) {
	return file_headersync_headersync_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderSyncResponse) GetHeader() []*block.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HeaderSyncResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HeaderSyncResponse) GetAck() *ack.Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *HeaderSyncResponse) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

var File_headersync_headersync_proto protoreflect.FileDescriptor

const file_headersync_headersync_proto_rawDesc = "" +
	"\n" +
	"\x1bheadersync/headersync.proto\x12\n" +
	"headersync\x1a\x11tagging/tag.proto\x1a\rack/ack.proto\x1a\x11block/block.proto\x1a\x11phase/phase.proto\"\x8d\x01\n" +
	"\x11HeaderSyncRequest\x12\x1e\n" +
	"\x03tag\x18\x01 \x01(\v2\f.tagging.TagR\x03tag\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x1a\n" +
	"\x03ack\x18\x03 \x01(\v2\b.ack.AckR\x03ack\x12\"\n" +
	"\x05phase\x18\x04 \x01(\v2\f.phase.PhaseR\x05phase\"\x95\x01\n" +
	"\x12HeaderSyncResponse\x12%\n" +
	"\x06header\x18\x01 \x03(\v2\r.block.HeaderR\x06header\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x1a\n" +
	"\x03ack\x18\x03 \x01(\v2\b.ack.AckR\x03ack\x12\"\n" +
	"\x05phase\x18\x04 \x01(\v2\f.phase.PhaseR\x05phaseBBZ@github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/headersyncb\x06proto3"

var (
	file_headersync_headersync_proto_rawDescOnce sync.Once
	file_headersync_headersync_proto_rawDescData []byte
)

func file_headersync_headersync_proto_rawDescGZIP() []byte {
	file_headersync_headersync_proto_rawDescOnce.Do(func() {
		file_headersync_headersync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_headersync_headersync_proto_rawDesc), len(file_headersync_headersync_proto_rawDesc)))
	})
	return file_headersync_headersync_proto_rawDescData
}

var file_headersync_headersync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_headersync_headersync_proto_goTypes = []any{
	(*HeaderSyncRequest)(nil),  // 0: headersync.HeaderSyncRequest
	(*HeaderSyncResponse)(nil), // 1: headersync.HeaderSyncResponse
	(*tagging.Tag)(nil),        // 2: tagging.Tag
	(*ack.Ack)(nil),            // 3: ack.Ack
	(*phase.Phase)(nil),        // 4: phase.Phase
	(*block.Header)(nil),       // 5: block.Header
}
var file_headersync_headersync_proto_depIdxs = []int32{
	2, // 0: headersync.HeaderSyncRequest.tag:type_name -> tagging.Tag
	3, // 1: headersync.HeaderSyncRequest.ack:type_name -> ack.Ack
	4, // 2: headersync.HeaderSyncRequest.phase:type_name -> phase.Phase
	5, // 3: headersync.HeaderSyncResponse.header:type_name -> block.Header
	3, // 4: headersync.HeaderSyncResponse.ack:type_name -> ack.Ack
	4, // 5: headersync.HeaderSyncResponse.phase:type_name -> phase.Phase
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_headersync_headersync_proto_init() }
func file_headersync_headersync_proto_init() {
	if File_headersync_headersync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_headersync_headersync_proto_rawDesc), len(file_headersync_headersync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_headersync_headersync_proto_goTypes,
		DependencyIndexes: file_headersync_headersync_proto_depIdxs,
		MessageInfos:      file_headersync_headersync_proto_msgTypes,
	}.Build()
	File_headersync_headersync_proto = out.File
	file_headersync_headersync_proto_goTypes = nil
	file_headersync_headersync_proto_depIdxs = nil
}
