// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: pubsub/pubsub.proto

package pubsub

import (
	auth "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/availability/auth"
	block "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/block"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscribeRequest is sent by the client when opening the stream.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Auth          *auth.Auth             `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_pubsub_pubsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_pubsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pubsub_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SubscribeRequest) GetAuth() *auth.Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

// SubscribeResponse is sent by the server to accept or reject the subscription.
type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_pubsub_pubsub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_pubsub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_pubsub_pubsub_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubscribeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PubSubDone signals the client that the server has stopped publishing.
type PubSubDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubSubDone) Reset() {
	*x = PubSubDone{}
	mi := &file_pubsub_pubsub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSubDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubDone) ProtoMessage() {}

func (x *PubSubDone) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_pubsub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubDone.ProtoReflect.Descriptor instead.
func (*PubSubDone) Descriptor() ([]byte, []int) {
	return file_pubsub_pubsub_proto_rawDescGZIP(), []int{2}
}

func (x *PubSubDone) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// BlockPubSubMessage is the streaming envelope pushed from server to client.
// Exactly one of the oneof fields will be set per message.
type BlockPubSubMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BlockPubSubMessage_Block
	//	*BlockPubSubMessage_Done
	Payload       isBlockPubSubMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPubSubMessage) Reset() {
	*x = BlockPubSubMessage{}
	mi := &file_pubsub_pubsub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPubSubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPubSubMessage) ProtoMessage() {}

func (x *BlockPubSubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_pubsub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPubSubMessage.ProtoReflect.Descriptor instead.
func (*BlockPubSubMessage) Descriptor() ([]byte, []int) {
	return file_pubsub_pubsub_proto_rawDescGZIP(), []int{3}
}

func (x *BlockPubSubMessage) GetPayload() isBlockPubSubMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BlockPubSubMessage) GetBlock() *block.ZKBlock {
	if x != nil {
		if x, ok := x.Payload.(*BlockPubSubMessage_Block); ok {
			return x.Block
		}
	}
	return nil
}

func (x *BlockPubSubMessage) GetDone() *PubSubDone {
	if x != nil {
		if x, ok := x.Payload.(*BlockPubSubMessage_Done); ok {
			return x.Done
		}
	}
	return nil
}

type isBlockPubSubMessage_Payload interface {
	isBlockPubSubMessage_Payload()
}

type BlockPubSubMessage_Block struct {
	Block *block.ZKBlock `protobuf:"bytes,1,opt,name=block,proto3,oneof"`
}

type BlockPubSubMessage_Done struct {
	Done *PubSubDone `protobuf:"bytes,2,opt,name=done,proto3,oneof"`
}

func (*BlockPubSubMessage_Block) isBlockPubSubMessage_Payload() {}

func (*BlockPubSubMessage_Done) isBlockPubSubMessage_Payload() {}

var File_pubsub_pubsub_proto protoreflect.FileDescriptor

const file_pubsub_pubsub_proto_rawDesc = "" +
	"\n" +
	"\x13pubsub/pubsub.proto\x12\x06pubsub\x1a\x11block/block.proto\x1a\x1cavailability/auth/auth.proto\"K\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1e\n" +
	"\x04auth\x18\x02 \x01(\v2\n" +
	".auth.AuthR\x04auth\"E\n" +
	"\x11SubscribeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"$\n" +
	"\n" +
	"PubSubDone\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"q\n" +
	"\x12BlockPubSubMessage\x12&\n" +
	"\x05block\x18\x01 \x01(\v2\x0e.block.ZKBlockH\x00R\x05block\x12(\n" +
	"\x04done\x18\x02 \x01(\v2\x12.pubsub.PubSubDoneH\x00R\x04doneB\t\n" +
	"\apayloadB>Z<github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/pubsubb\x06proto3"

var (
	file_pubsub_pubsub_proto_rawDescOnce sync.Once
	file_pubsub_pubsub_proto_rawDescData []byte
)

func file_pubsub_pubsub_proto_rawDescGZIP() []byte {
	file_pubsub_pubsub_proto_rawDescOnce.Do(func() {
		file_pubsub_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pubsub_pubsub_proto_rawDesc), len(file_pubsub_pubsub_proto_rawDesc)))
	})
	return file_pubsub_pubsub_proto_rawDescData
}

var file_pubsub_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pubsub_pubsub_proto_goTypes = []any{
	(*SubscribeRequest)(nil),   // 0: pubsub.SubscribeRequest
	(*SubscribeResponse)(nil),  // 1: pubsub.SubscribeResponse
	(*PubSubDone)(nil),         // 2: pubsub.PubSubDone
	(*BlockPubSubMessage)(nil), // 3: pubsub.BlockPubSubMessage
	(*auth.Auth)(nil),          // 4: auth.Auth
	(*block.ZKBlock)(nil),      // 5: block.ZKBlock
}
var file_pubsub_pubsub_proto_depIdxs = []int32{
	4, // 0: pubsub.SubscribeRequest.auth:type_name -> auth.Auth
	5, // 1: pubsub.BlockPubSubMessage.block:type_name -> block.ZKBlock
	2, // 2: pubsub.BlockPubSubMessage.done:type_name -> pubsub.PubSubDone
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pubsub_pubsub_proto_init() }
func file_pubsub_pubsub_proto_init() {
	if File_pubsub_pubsub_proto != nil {
		return
	}
	file_pubsub_pubsub_proto_msgTypes[3].OneofWrappers = []any{
		(*BlockPubSubMessage_Block)(nil),
		(*BlockPubSubMessage_Done)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pubsub_pubsub_proto_rawDesc), len(file_pubsub_pubsub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pubsub_pubsub_proto_goTypes,
		DependencyIndexes: file_pubsub_pubsub_proto_depIdxs,
		MessageInfos:      file_pubsub_pubsub_proto_msgTypes,
	}.Build()
	File_pubsub_pubsub_proto = out.File
	file_pubsub_pubsub_proto_goTypes = nil
	file_pubsub_pubsub_proto_depIdxs = nil
}
