// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: datasync/datasync.proto

package datasync

import (
	ack "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/ack"
	block "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/block"
	phase "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/phase"
	tagging "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/tagging"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *tagging.Tag           `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"` // blocks being requested (ranges or individual)
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Ack           *ack.Ack               `protobuf:"bytes,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Phase         *phase.Phase           `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSyncRequest) Reset() {
	*x = DataSyncRequest{}
	mi := &file_datasync_datasync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSyncRequest) ProtoMessage() {}

func (x *DataSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasync_datasync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSyncRequest.ProtoReflect.Descriptor instead.
func (*DataSyncRequest) Descriptor() ([]byte, []int) {
	return file_datasync_datasync_proto_rawDescGZIP(), []int{0}
}

func (x *DataSyncRequest) GetTag() *tagging.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *DataSyncRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DataSyncRequest) GetAck() *ack.Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *DataSyncRequest) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

type DataSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*block.NonHeaders    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Ack           *ack.Ack               `protobuf:"bytes,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Phase         *phase.Phase           `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSyncResponse) Reset() {
	*x = DataSyncResponse{}
	mi := &file_datasync_datasync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSyncResponse) ProtoMessage() {}

func (x *DataSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasync_datasync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSyncResponse.ProtoReflect.Descriptor instead.
func (*DataSyncResponse) Descriptor() ([]byte, []int) {
	return file_datasync_datasync_proto_rawDescGZIP(), []int{1}
}

func (x *DataSyncResponse) GetData() []*block.NonHeaders {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataSyncResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DataSyncResponse) GetAck() *ack.Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *DataSyncResponse) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

var File_datasync_datasync_proto protoreflect.FileDescriptor

const file_datasync_datasync_proto_rawDesc = "" +
	"\n" +
	"\x17datasync/datasync.proto\x12\bdatasync\x1a\rack/ack.proto\x1a\x11phase/phase.proto\x1a\x1bblock/block_nonheader.proto\x1a\x11tagging/tag.proto\"\x8b\x01\n" +
	"\x0fDataSyncRequest\x12\x1e\n" +
	"\x03tag\x18\x01 \x01(\v2\f.tagging.TagR\x03tag\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x1a\n" +
	"\x03ack\x18\x03 \x01(\v2\b.ack.AckR\x03ack\x12\"\n" +
	"\x05phase\x18\x04 \x01(\v2\f.phase.PhaseR\x05phase\"\x93\x01\n" +
	"\x10DataSyncResponse\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.block.NonHeadersR\x04data\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x1a\n" +
	"\x03ack\x18\x03 \x01(\v2\b.ack.AckR\x03ack\x12\"\n" +
	"\x05phase\x18\x04 \x01(\v2\f.phase.PhaseR\x05phaseB@Z>github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/datasyncb\x06proto3"

var (
	file_datasync_datasync_proto_rawDescOnce sync.Once
	file_datasync_datasync_proto_rawDescData []byte
)

func file_datasync_datasync_proto_rawDescGZIP() []byte {
	file_datasync_datasync_proto_rawDescOnce.Do(func() {
		file_datasync_datasync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datasync_datasync_proto_rawDesc), len(file_datasync_datasync_proto_rawDesc)))
	})
	return file_datasync_datasync_proto_rawDescData
}

var file_datasync_datasync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_datasync_datasync_proto_goTypes = []any{
	(*DataSyncRequest)(nil),  // 0: datasync.DataSyncRequest
	(*DataSyncResponse)(nil), // 1: datasync.DataSyncResponse
	(*tagging.Tag)(nil),      // 2: tagging.Tag
	(*ack.Ack)(nil),          // 3: ack.Ack
	(*phase.Phase)(nil),      // 4: phase.Phase
	(*block.NonHeaders)(nil), // 5: block.NonHeaders
}
var file_datasync_datasync_proto_depIdxs = []int32{
	2, // 0: datasync.DataSyncRequest.tag:type_name -> tagging.Tag
	3, // 1: datasync.DataSyncRequest.ack:type_name -> ack.Ack
	4, // 2: datasync.DataSyncRequest.phase:type_name -> phase.Phase
	5, // 3: datasync.DataSyncResponse.data:type_name -> block.NonHeaders
	3, // 4: datasync.DataSyncResponse.ack:type_name -> ack.Ack
	4, // 5: datasync.DataSyncResponse.phase:type_name -> phase.Phase
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_datasync_datasync_proto_init() }
func file_datasync_datasync_proto_init() {
	if File_datasync_datasync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datasync_datasync_proto_rawDesc), len(file_datasync_datasync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datasync_datasync_proto_goTypes,
		DependencyIndexes: file_datasync_datasync_proto_depIdxs,
		MessageInfos:      file_datasync_datasync_proto_msgTypes,
	}.Build()
	File_datasync_datasync_proto = out.File
	file_datasync_datasync_proto_goTypes = nil
	file_datasync_datasync_proto_depIdxs = nil
}
