// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: accounts/accounts.proto

package accounts

import (
	ack "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/ack"
	checksum "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/checksum"
	phase "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/phase"
	tagging "github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/tagging"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account is the persisted account record (mirrors types.Account in common/types/Block.go).
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Legacy DID fields (for backward compatibility)
	DidAddress string `protobuf:"bytes,1,opt,name=did_address,json=didAddress,proto3" json:"did_address,omitempty"`
	// New PublicKey-based fields; 20-byte Ethereum-style address (derived from PublicKey)
	Address []byte `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// balance is always "0" when transferred during AccountSync.
	// Actual balance is computed later by the Reconciliation phase.
	Balance string `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce   uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Account metadata
	AccountType string `protobuf:"bytes,5,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"` // "did" or "publickey"
	CreatedAt   int64  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   int64  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Optional arbitrary metadata (maps from map[string]interface{} on the wire)
	Metadata      *structpb.Struct `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_accounts_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_accounts_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetDidAddress() string {
	if x != nil {
		return x.DidAddress
	}
	return ""
}

func (x *Account) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Account) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *Account) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Account) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Account) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Account) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Account) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// AccountNonceSyncRequest is one frame of the client→server upload stream.
// The client sends multiple requests sequentially, one per ART chunk.
// Each chunk covers at most MAX_ACCOUNT_NONCES keys.
//
// Frame structure (from architecture):
//
//	ART        — zstd-compressed ART of nonces the client already has
//	TotalKeys  — client's full account count (lets server know how many batches to expect)
//	KeysRange  — nonce range this chunk covers (enables O(1) segment routing on server)
//	Checksum — checksum.Checksum (value + ChecksumVersion) over `art`; when value is
//	               non-empty, server uses this and ignores field 4.
//	Phase      — phase information
type AccountNonceSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Art           []byte                 `protobuf:"bytes,1,opt,name=art,proto3" json:"art,omitempty"`                                  // zstd-compressed ART chunk (art.Encode output)
	TotalKeys     uint64                 `protobuf:"varint,2,opt,name=total_keys,json=totalKeys,proto3" json:"total_keys,omitempty"`    // client's total account count across ALL chunks
	KeysRange     *tagging.RangeTag      `protobuf:"bytes,3,opt,name=keys_range,json=keysRange,proto3" json:"keys_range,omitempty"`     // nonce range [start, end] for this chunk
	BatchIndex    uint32                 `protobuf:"varint,5,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"` // 0-indexed sequence number
	IsLast        bool                   `protobuf:"varint,6,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`             // true on the final batch — server starts diff computation after this
	Phase         *phase.Phase           `protobuf:"bytes,7,opt,name=phase,proto3" json:"phase,omitempty"`                              // phase information
	Checksum      *checksum.Checksum     `protobuf:"bytes,8,opt,name=checksum,proto3" json:"checksum,omitempty"`                        // optional: versioned digest (shared checksum.proto)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountNonceSyncRequest) Reset() {
	*x = AccountNonceSyncRequest{}
	mi := &file_accounts_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountNonceSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountNonceSyncRequest) ProtoMessage() {}

func (x *AccountNonceSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountNonceSyncRequest.ProtoReflect.Descriptor instead.
func (*AccountNonceSyncRequest) Descriptor() ([]byte, []int) {
	return file_accounts_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *AccountNonceSyncRequest) GetArt() []byte {
	if x != nil {
		return x.Art
	}
	return nil
}

func (x *AccountNonceSyncRequest) GetTotalKeys() uint64 {
	if x != nil {
		return x.TotalKeys
	}
	return 0
}

func (x *AccountNonceSyncRequest) GetKeysRange() *tagging.RangeTag {
	if x != nil {
		return x.KeysRange
	}
	return nil
}

func (x *AccountNonceSyncRequest) GetBatchIndex() uint32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *AccountNonceSyncRequest) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *AccountNonceSyncRequest) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

func (x *AccountNonceSyncRequest) GetChecksum() *checksum.Checksum {
	if x != nil {
		return x.Checksum
	}
	return nil
}

// AccountBatchAck acknowledges receipt of one ART batch.
// Client waits for this before sending the next batch.
type AccountBatchAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchIndex    uint32                 `protobuf:"varint,1,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	Ack           *ack.Ack               `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountBatchAck) Reset() {
	*x = AccountBatchAck{}
	mi := &file_accounts_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBatchAck) ProtoMessage() {}

func (x *AccountBatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBatchAck.ProtoReflect.Descriptor instead.
func (*AccountBatchAck) Descriptor() ([]byte, []int) {
	return file_accounts_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *AccountBatchAck) GetBatchIndex() uint32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *AccountBatchAck) GetAck() *ack.Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

// AccountSyncHeartbeat is sent by the server during the diff computation gap
// (between the last AccountBatchAck and the first AccountSyncResponse page)
// to keep the stream alive when the server is scanning a large account set.
type AccountSyncHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix nanoseconds — for observability only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSyncHeartbeat) Reset() {
	*x = AccountSyncHeartbeat{}
	mi := &file_accounts_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSyncHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSyncHeartbeat) ProtoMessage() {}

func (x *AccountSyncHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSyncHeartbeat.ProtoReflect.Descriptor instead.
func (*AccountSyncHeartbeat) Descriptor() ([]byte, []int) {
	return file_accounts_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *AccountSyncHeartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// AccountSyncResponse carries one page of accounts the client is missing.
// Pages are sent in parallel — this message carries NO completion signal.
// Do NOT use the absence of more messages to infer completion; wait for
// AccountSyncEndOfStream instead.
// Client writes each received account with balance="0"; Reconciliation fills
// in actual balances later for accounts that had transactions.
type AccountSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`                     // accounts client does not have
	PageIndex     uint32                 `protobuf:"varint,2,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"` // page index for reordering out-of-order arrivals
	Ack           *ack.Ack               `protobuf:"bytes,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Phase         *phase.Phase           `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSyncResponse) Reset() {
	*x = AccountSyncResponse{}
	mi := &file_accounts_accounts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSyncResponse) ProtoMessage() {}

func (x *AccountSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accounts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSyncResponse.ProtoReflect.Descriptor instead.
func (*AccountSyncResponse) Descriptor() ([]byte, []int) {
	return file_accounts_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *AccountSyncResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *AccountSyncResponse) GetPageIndex() uint32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *AccountSyncResponse) GetAck() *ack.Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *AccountSyncResponse) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

// AccountSyncEndOfStream is sent by the server exactly once, sequentially,
// after ALL parallel AccountSyncResponse pages have been fully dispatched
// (server waits on a WaitGroup for all page goroutines before sending this).
//
// This is the only reliable completion signal. Because response pages arrive
// out of order, a has_more=false flag on a response page could arrive before
// other in-transit pages — causing the client to stop reading and lose data.
// Sending this as a sequential message after all pages guarantees it always
// arrives last.
//
// Client reads AccountSyncResponse frames freely until this message arrives.
// Use total_pages to verify no pages were lost:
//
//	received_pages != total_pages → a page was dropped, trigger a retry.
type AccountSyncEndOfStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPages    uint32                 `protobuf:"varint,1,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`          // total AccountSyncResponse pages dispatched
	TotalAccounts uint64                 `protobuf:"varint,2,opt,name=total_accounts,json=totalAccounts,proto3" json:"total_accounts,omitempty"` // total missing accounts transferred across all pages
	Ack           *ack.Ack               `protobuf:"bytes,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Phase         *phase.Phase           `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSyncEndOfStream) Reset() {
	*x = AccountSyncEndOfStream{}
	mi := &file_accounts_accounts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSyncEndOfStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSyncEndOfStream) ProtoMessage() {}

func (x *AccountSyncEndOfStream) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accounts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSyncEndOfStream.ProtoReflect.Descriptor instead.
func (*AccountSyncEndOfStream) Descriptor() ([]byte, []int) {
	return file_accounts_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *AccountSyncEndOfStream) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *AccountSyncEndOfStream) GetTotalAccounts() uint64 {
	if x != nil {
		return x.TotalAccounts
	}
	return 0
}

func (x *AccountSyncEndOfStream) GetAck() *ack.Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *AccountSyncEndOfStream) GetPhase() *phase.Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

// AccountSyncServerMessage is the wire envelope for all server→client frames.
// The server sends messages in this sequence:
//  1. N × AccountBatchAck      — one per received ART batch (sequential)
//  2. M × AccountSyncHeartbeat — during diff computation gap (sequential, if needed)
//  3. P × AccountSyncResponse  — missing account pages (parallel)
//  4. 1 × AccountSyncEndOfStream — sent sequentially after all P pages complete
type AccountSyncServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AccountSyncServerMessage_BatchAck
	//	*AccountSyncServerMessage_Heartbeat
	//	*AccountSyncServerMessage_Response
	//	*AccountSyncServerMessage_End
	Payload       isAccountSyncServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSyncServerMessage) Reset() {
	*x = AccountSyncServerMessage{}
	mi := &file_accounts_accounts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSyncServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSyncServerMessage) ProtoMessage() {}

func (x *AccountSyncServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accounts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSyncServerMessage.ProtoReflect.Descriptor instead.
func (*AccountSyncServerMessage) Descriptor() ([]byte, []int) {
	return file_accounts_accounts_proto_rawDescGZIP(), []int{6}
}

func (x *AccountSyncServerMessage) GetPayload() isAccountSyncServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AccountSyncServerMessage) GetBatchAck() *AccountBatchAck {
	if x != nil {
		if x, ok := x.Payload.(*AccountSyncServerMessage_BatchAck); ok {
			return x.BatchAck
		}
	}
	return nil
}

func (x *AccountSyncServerMessage) GetHeartbeat() *AccountSyncHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AccountSyncServerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AccountSyncServerMessage) GetResponse() *AccountSyncResponse {
	if x != nil {
		if x, ok := x.Payload.(*AccountSyncServerMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *AccountSyncServerMessage) GetEnd() *AccountSyncEndOfStream {
	if x != nil {
		if x, ok := x.Payload.(*AccountSyncServerMessage_End); ok {
			return x.End
		}
	}
	return nil
}

type isAccountSyncServerMessage_Payload interface {
	isAccountSyncServerMessage_Payload()
}

type AccountSyncServerMessage_BatchAck struct {
	BatchAck *AccountBatchAck `protobuf:"bytes,1,opt,name=batch_ack,json=batchAck,proto3,oneof"`
}

type AccountSyncServerMessage_Heartbeat struct {
	Heartbeat *AccountSyncHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AccountSyncServerMessage_Response struct {
	Response *AccountSyncResponse `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

type AccountSyncServerMessage_End struct {
	End *AccountSyncEndOfStream `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

func (*AccountSyncServerMessage_BatchAck) isAccountSyncServerMessage_Payload() {}

func (*AccountSyncServerMessage_Heartbeat) isAccountSyncServerMessage_Payload() {}

func (*AccountSyncServerMessage_Response) isAccountSyncServerMessage_Payload() {}

func (*AccountSyncServerMessage_End) isAccountSyncServerMessage_Payload() {}

var File_accounts_accounts_proto protoreflect.FileDescriptor

const file_accounts_accounts_proto_rawDesc = "" +
	"\n" +
	"\x17accounts/accounts.proto\x12\baccounts\x1a\x1cgoogle/protobuf/struct.proto\x1a\rack/ack.proto\x1a\x11phase/phase.proto\x1a\x11tagging/tag.proto\x1a\x17checksum/checksum.proto\"\x8a\x02\n" +
	"\aAccount\x12\x1f\n" +
	"\vdid_address\x18\x01 \x01(\tR\n" +
	"didAddress\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12\x18\n" +
	"\abalance\x18\x03 \x01(\tR\abalance\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\x12!\n" +
	"\faccount_type\x18\x05 \x01(\tR\vaccountType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x8a\x02\n" +
	"\x17AccountNonceSyncRequest\x12\x10\n" +
	"\x03art\x18\x01 \x01(\fR\x03art\x12\x1d\n" +
	"\n" +
	"total_keys\x18\x02 \x01(\x04R\ttotalKeys\x120\n" +
	"\n" +
	"keys_range\x18\x03 \x01(\v2\x11.tagging.RangeTagR\tkeysRange\x12\x1f\n" +
	"\vbatch_index\x18\x05 \x01(\rR\n" +
	"batchIndex\x12\x17\n" +
	"\ais_last\x18\x06 \x01(\bR\x06isLast\x12\"\n" +
	"\x05phase\x18\a \x01(\v2\f.phase.PhaseR\x05phase\x12.\n" +
	"\bchecksum\x18\b \x01(\v2\x12.checksum.ChecksumR\bchecksum\"N\n" +
	"\x0fAccountBatchAck\x12\x1f\n" +
	"\vbatch_index\x18\x01 \x01(\rR\n" +
	"batchIndex\x12\x1a\n" +
	"\x03ack\x18\x02 \x01(\v2\b.ack.AckR\x03ack\"4\n" +
	"\x14AccountSyncHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xa3\x01\n" +
	"\x13AccountSyncResponse\x12-\n" +
	"\baccounts\x18\x01 \x03(\v2\x11.accounts.AccountR\baccounts\x12\x1d\n" +
	"\n" +
	"page_index\x18\x02 \x01(\rR\tpageIndex\x12\x1a\n" +
	"\x03ack\x18\x03 \x01(\v2\b.ack.AckR\x03ack\x12\"\n" +
	"\x05phase\x18\x04 \x01(\v2\f.phase.PhaseR\x05phase\"\xa0\x01\n" +
	"\x16AccountSyncEndOfStream\x12\x1f\n" +
	"\vtotal_pages\x18\x01 \x01(\rR\n" +
	"totalPages\x12%\n" +
	"\x0etotal_accounts\x18\x02 \x01(\x04R\rtotalAccounts\x12\x1a\n" +
	"\x03ack\x18\x03 \x01(\v2\b.ack.AckR\x03ack\x12\"\n" +
	"\x05phase\x18\x04 \x01(\v2\f.phase.PhaseR\x05phase\"\x92\x02\n" +
	"\x18AccountSyncServerMessage\x128\n" +
	"\tbatch_ack\x18\x01 \x01(\v2\x19.accounts.AccountBatchAckH\x00R\bbatchAck\x12>\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1e.accounts.AccountSyncHeartbeatH\x00R\theartbeat\x12;\n" +
	"\bresponse\x18\x03 \x01(\v2\x1d.accounts.AccountSyncResponseH\x00R\bresponse\x124\n" +
	"\x03end\x18\x04 \x01(\v2 .accounts.AccountSyncEndOfStreamH\x00R\x03endB\t\n" +
	"\apayloadB@Z>github.com/JupiterMetaLabs/JMDN-FastSync/common/proto/accountsb\x06proto3"

var (
	file_accounts_accounts_proto_rawDescOnce sync.Once
	file_accounts_accounts_proto_rawDescData []byte
)

func file_accounts_accounts_proto_rawDescGZIP() []byte {
	file_accounts_accounts_proto_rawDescOnce.Do(func() {
		file_accounts_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_accounts_proto_rawDesc), len(file_accounts_accounts_proto_rawDesc)))
	})
	return file_accounts_accounts_proto_rawDescData
}

var file_accounts_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_accounts_accounts_proto_goTypes = []any{
	(*Account)(nil),                  // 0: accounts.Account
	(*AccountNonceSyncRequest)(nil),  // 1: accounts.AccountNonceSyncRequest
	(*AccountBatchAck)(nil),          // 2: accounts.AccountBatchAck
	(*AccountSyncHeartbeat)(nil),     // 3: accounts.AccountSyncHeartbeat
	(*AccountSyncResponse)(nil),      // 4: accounts.AccountSyncResponse
	(*AccountSyncEndOfStream)(nil),   // 5: accounts.AccountSyncEndOfStream
	(*AccountSyncServerMessage)(nil), // 6: accounts.AccountSyncServerMessage
	(*structpb.Struct)(nil),          // 7: google.protobuf.Struct
	(*tagging.RangeTag)(nil),         // 8: tagging.RangeTag
	(*phase.Phase)(nil),              // 9: phase.Phase
	(*checksum.Checksum)(nil),        // 10: checksum.Checksum
	(*ack.Ack)(nil),                  // 11: ack.Ack
}
var file_accounts_accounts_proto_depIdxs = []int32{
	7,  // 0: accounts.Account.metadata:type_name -> google.protobuf.Struct
	8,  // 1: accounts.AccountNonceSyncRequest.keys_range:type_name -> tagging.RangeTag
	9,  // 2: accounts.AccountNonceSyncRequest.phase:type_name -> phase.Phase
	10, // 3: accounts.AccountNonceSyncRequest.checksum:type_name -> checksum.Checksum
	11, // 4: accounts.AccountBatchAck.ack:type_name -> ack.Ack
	0,  // 5: accounts.AccountSyncResponse.accounts:type_name -> accounts.Account
	11, // 6: accounts.AccountSyncResponse.ack:type_name -> ack.Ack
	9,  // 7: accounts.AccountSyncResponse.phase:type_name -> phase.Phase
	11, // 8: accounts.AccountSyncEndOfStream.ack:type_name -> ack.Ack
	9,  // 9: accounts.AccountSyncEndOfStream.phase:type_name -> phase.Phase
	2,  // 10: accounts.AccountSyncServerMessage.batch_ack:type_name -> accounts.AccountBatchAck
	3,  // 11: accounts.AccountSyncServerMessage.heartbeat:type_name -> accounts.AccountSyncHeartbeat
	4,  // 12: accounts.AccountSyncServerMessage.response:type_name -> accounts.AccountSyncResponse
	5,  // 13: accounts.AccountSyncServerMessage.end:type_name -> accounts.AccountSyncEndOfStream
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_accounts_accounts_proto_init() }
func file_accounts_accounts_proto_init() {
	if File_accounts_accounts_proto != nil {
		return
	}
	file_accounts_accounts_proto_msgTypes[6].OneofWrappers = []any{
		(*AccountSyncServerMessage_BatchAck)(nil),
		(*AccountSyncServerMessage_Heartbeat)(nil),
		(*AccountSyncServerMessage_Response)(nil),
		(*AccountSyncServerMessage_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_accounts_proto_rawDesc), len(file_accounts_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accounts_accounts_proto_goTypes,
		DependencyIndexes: file_accounts_accounts_proto_depIdxs,
		MessageInfos:      file_accounts_accounts_proto_msgTypes,
	}.Build()
	File_accounts_accounts_proto = out.File
	file_accounts_accounts_proto_goTypes = nil
	file_accounts_accounts_proto_depIdxs = nil
}
